template: testify
dir: internal/provider/mocks
filename: "{{.InterfaceName}}.go"
pkgname: mocks
structname: "{{.InterfaceName}}"
force-file-write: true
formatter: gofmt
packages:
  github.com/catonetworks/terraform-provider-cato/internal/provider:
    interfaces:
      InternetFirewallBulkPolicyClient:
      InternetFirewallPolicyClient:
      InternetFirewallSubPolicyClient:
      StaticHostClient:
      WanFirewallBulkPolicyClient:
      WanFirewallSubPolicyClient:
  github.com/catonetworks/terraform-provider-cato/internal/provider/network/netrange/adapter:
    interfaces:
      NetworkRangeClient:
  github.com/catonetworks/terraform-provider-cato/internal/provider/network/sktsite/adapter:
    interfaces:
      SocketSiteClient:
  github.com/catonetworks/terraform-provider-cato/internal/provider/network/netrange/application:
    interfaces:
      NetworkRangePort:
  github.com/catonetworks/terraform-provider-cato/internal/provider/network/sktsite/application:
    interfaces:
      SocketSitePort:
