// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Yamashou/gqlgenc/clientv2"
	cato_go_sdk "github.com/catonetworks/cato-go-sdk"
	cato_models "github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewBgpPeerClient creates a new instance of BgpPeerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBgpPeerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BgpPeerClient {
	mock := &BgpPeerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BgpPeerClient is an autogenerated mock type for the BgpPeerClient type
type BgpPeerClient struct {
	mock.Mock
}

type BgpPeerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BgpPeerClient) EXPECT() *BgpPeerClient_Expecter {
	return &BgpPeerClient_Expecter{mock: &_m.Mock}
}

// SiteAddBgpPeer provides a mock function for the type BgpPeerClient
func (_mock *BgpPeerClient) SiteAddBgpPeer(ctx context.Context, input cato_models.AddBgpPeerInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteAddBgpPeer, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, input, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, input, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SiteAddBgpPeer")
	}

	var r0 *cato_go_sdk.SiteAddBgpPeer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.AddBgpPeerInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteAddBgpPeer, error)); ok {
		return returnFunc(ctx, input, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.AddBgpPeerInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.SiteAddBgpPeer); ok {
		r0 = returnFunc(ctx, input, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.SiteAddBgpPeer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.AddBgpPeerInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, input, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BgpPeerClient_SiteAddBgpPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SiteAddBgpPeer'
type BgpPeerClient_SiteAddBgpPeer_Call struct {
	*mock.Call
}

// SiteAddBgpPeer is a helper method to define mock.On call
//   - ctx context.Context
//   - input cato_models.AddBgpPeerInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BgpPeerClient_Expecter) SiteAddBgpPeer(ctx interface{}, input interface{}, accountID interface{}, interceptors ...interface{}) *BgpPeerClient_SiteAddBgpPeer_Call {
	return &BgpPeerClient_SiteAddBgpPeer_Call{Call: _e.mock.On("SiteAddBgpPeer",
		append([]interface{}{ctx, input, accountID}, interceptors...)...)}
}

func (_c *BgpPeerClient_SiteAddBgpPeer_Call) Run(run func(ctx context.Context, input cato_models.AddBgpPeerInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *BgpPeerClient_SiteAddBgpPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.AddBgpPeerInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.AddBgpPeerInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *BgpPeerClient_SiteAddBgpPeer_Call) Return(siteAddBgpPeer *cato_go_sdk.SiteAddBgpPeer, err error) *BgpPeerClient_SiteAddBgpPeer_Call {
	_c.Call.Return(siteAddBgpPeer, err)
	return _c
}

func (_c *BgpPeerClient_SiteAddBgpPeer_Call) RunAndReturn(run func(ctx context.Context, input cato_models.AddBgpPeerInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteAddBgpPeer, error)) *BgpPeerClient_SiteAddBgpPeer_Call {
	_c.Call.Return(run)
	return _c
}

// SiteBgpPeer provides a mock function for the type BgpPeerClient
func (_mock *BgpPeerClient) SiteBgpPeer(ctx context.Context, input cato_models.BgpPeerRefInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Site, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, input, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, input, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SiteBgpPeer")
	}

	var r0 *cato_go_sdk.Site
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.BgpPeerRefInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.Site, error)); ok {
		return returnFunc(ctx, input, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.BgpPeerRefInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.Site); ok {
		r0 = returnFunc(ctx, input, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.Site)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.BgpPeerRefInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, input, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BgpPeerClient_SiteBgpPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SiteBgpPeer'
type BgpPeerClient_SiteBgpPeer_Call struct {
	*mock.Call
}

// SiteBgpPeer is a helper method to define mock.On call
//   - ctx context.Context
//   - input cato_models.BgpPeerRefInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BgpPeerClient_Expecter) SiteBgpPeer(ctx interface{}, input interface{}, accountID interface{}, interceptors ...interface{}) *BgpPeerClient_SiteBgpPeer_Call {
	return &BgpPeerClient_SiteBgpPeer_Call{Call: _e.mock.On("SiteBgpPeer",
		append([]interface{}{ctx, input, accountID}, interceptors...)...)}
}

func (_c *BgpPeerClient_SiteBgpPeer_Call) Run(run func(ctx context.Context, input cato_models.BgpPeerRefInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *BgpPeerClient_SiteBgpPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.BgpPeerRefInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.BgpPeerRefInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *BgpPeerClient_SiteBgpPeer_Call) Return(site *cato_go_sdk.Site, err error) *BgpPeerClient_SiteBgpPeer_Call {
	_c.Call.Return(site, err)
	return _c
}

func (_c *BgpPeerClient_SiteBgpPeer_Call) RunAndReturn(run func(ctx context.Context, input cato_models.BgpPeerRefInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Site, error)) *BgpPeerClient_SiteBgpPeer_Call {
	_c.Call.Return(run)
	return _c
}

// SiteRemoveBgpPeer provides a mock function for the type BgpPeerClient
func (_mock *BgpPeerClient) SiteRemoveBgpPeer(ctx context.Context, input cato_models.RemoveBgpPeerInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteRemoveBgpPeer, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, input, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, input, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SiteRemoveBgpPeer")
	}

	var r0 *cato_go_sdk.SiteRemoveBgpPeer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.RemoveBgpPeerInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteRemoveBgpPeer, error)); ok {
		return returnFunc(ctx, input, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.RemoveBgpPeerInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.SiteRemoveBgpPeer); ok {
		r0 = returnFunc(ctx, input, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.SiteRemoveBgpPeer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.RemoveBgpPeerInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, input, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BgpPeerClient_SiteRemoveBgpPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SiteRemoveBgpPeer'
type BgpPeerClient_SiteRemoveBgpPeer_Call struct {
	*mock.Call
}

// SiteRemoveBgpPeer is a helper method to define mock.On call
//   - ctx context.Context
//   - input cato_models.RemoveBgpPeerInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BgpPeerClient_Expecter) SiteRemoveBgpPeer(ctx interface{}, input interface{}, accountID interface{}, interceptors ...interface{}) *BgpPeerClient_SiteRemoveBgpPeer_Call {
	return &BgpPeerClient_SiteRemoveBgpPeer_Call{Call: _e.mock.On("SiteRemoveBgpPeer",
		append([]interface{}{ctx, input, accountID}, interceptors...)...)}
}

func (_c *BgpPeerClient_SiteRemoveBgpPeer_Call) Run(run func(ctx context.Context, input cato_models.RemoveBgpPeerInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *BgpPeerClient_SiteRemoveBgpPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.RemoveBgpPeerInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.RemoveBgpPeerInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *BgpPeerClient_SiteRemoveBgpPeer_Call) Return(siteRemoveBgpPeer *cato_go_sdk.SiteRemoveBgpPeer, err error) *BgpPeerClient_SiteRemoveBgpPeer_Call {
	_c.Call.Return(siteRemoveBgpPeer, err)
	return _c
}

func (_c *BgpPeerClient_SiteRemoveBgpPeer_Call) RunAndReturn(run func(ctx context.Context, input cato_models.RemoveBgpPeerInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteRemoveBgpPeer, error)) *BgpPeerClient_SiteRemoveBgpPeer_Call {
	_c.Call.Return(run)
	return _c
}

// SiteUpdateBgpPeer provides a mock function for the type BgpPeerClient
func (_mock *BgpPeerClient) SiteUpdateBgpPeer(ctx context.Context, input cato_models.UpdateBgpPeerInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteUpdateBgpPeer, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, input, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, input, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SiteUpdateBgpPeer")
	}

	var r0 *cato_go_sdk.SiteUpdateBgpPeer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.UpdateBgpPeerInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteUpdateBgpPeer, error)); ok {
		return returnFunc(ctx, input, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.UpdateBgpPeerInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.SiteUpdateBgpPeer); ok {
		r0 = returnFunc(ctx, input, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.SiteUpdateBgpPeer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.UpdateBgpPeerInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, input, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BgpPeerClient_SiteUpdateBgpPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SiteUpdateBgpPeer'
type BgpPeerClient_SiteUpdateBgpPeer_Call struct {
	*mock.Call
}

// SiteUpdateBgpPeer is a helper method to define mock.On call
//   - ctx context.Context
//   - input cato_models.UpdateBgpPeerInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BgpPeerClient_Expecter) SiteUpdateBgpPeer(ctx interface{}, input interface{}, accountID interface{}, interceptors ...interface{}) *BgpPeerClient_SiteUpdateBgpPeer_Call {
	return &BgpPeerClient_SiteUpdateBgpPeer_Call{Call: _e.mock.On("SiteUpdateBgpPeer",
		append([]interface{}{ctx, input, accountID}, interceptors...)...)}
}

func (_c *BgpPeerClient_SiteUpdateBgpPeer_Call) Run(run func(ctx context.Context, input cato_models.UpdateBgpPeerInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *BgpPeerClient_SiteUpdateBgpPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.UpdateBgpPeerInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.UpdateBgpPeerInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *BgpPeerClient_SiteUpdateBgpPeer_Call) Return(siteUpdateBgpPeer *cato_go_sdk.SiteUpdateBgpPeer, err error) *BgpPeerClient_SiteUpdateBgpPeer_Call {
	_c.Call.Return(siteUpdateBgpPeer, err)
	return _c
}

func (_c *BgpPeerClient_SiteUpdateBgpPeer_Call) RunAndReturn(run func(ctx context.Context, input cato_models.UpdateBgpPeerInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteUpdateBgpPeer, error)) *BgpPeerClient_SiteUpdateBgpPeer_Call {
	_c.Call.Return(run)
	return _c
}
