// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/Yamashou/gqlgenc/clientv2"
	"github.com/catonetworks/cato-go-sdk"
	"github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewBulkInternetFirewallPolicyClient creates a new instance of BulkInternetFirewallPolicyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBulkInternetFirewallPolicyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BulkInternetFirewallPolicyClient {
	mock := &BulkInternetFirewallPolicyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BulkInternetFirewallPolicyClient is an autogenerated mock type for the BulkInternetFirewallPolicyClient type
type BulkInternetFirewallPolicyClient struct {
	mock.Mock
}

type BulkInternetFirewallPolicyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BulkInternetFirewallPolicyClient) EXPECT() *BulkInternetFirewallPolicyClient_Expecter {
	return &BulkInternetFirewallPolicyClient_Expecter{mock: &_m.Mock}
}

// PolicyInternetFirewallAddSection provides a mock function for the type BulkInternetFirewallPolicyClient
func (_mock *BulkInternetFirewallPolicyClient) PolicyInternetFirewallAddSection(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyAddSectionInput cato_models.PolicyAddSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddSection, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallAddSection")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallAddSection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyAddSectionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddSection, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyAddSectionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallAddSection); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallAddSection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyAddSectionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallAddSection'
type BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call struct {
	*mock.Call
}

// PolicyInternetFirewallAddSection is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyAddSectionInput cato_models.PolicyAddSectionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BulkInternetFirewallPolicyClient_Expecter) PolicyInternetFirewallAddSection(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyAddSectionInput interface{}, accountID interface{}, interceptors ...interface{}) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call {
	return &BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call{Call: _e.mock.On("PolicyInternetFirewallAddSection",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID}, interceptors...)...)}
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyAddSectionInput cato_models.PolicyAddSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.PolicyAddSectionInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.PolicyAddSectionInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call) Return(policyInternetFirewallAddSection *cato_go_sdk.PolicyInternetFirewallAddSection, err error) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call {
	_c.Call.Return(policyInternetFirewallAddSection, err)
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyAddSectionInput cato_models.PolicyAddSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddSection, error)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallAddSection_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallPublishPolicyRevision provides a mock function for the type BulkInternetFirewallPolicyClient
func (_mock *BulkInternetFirewallPolicyClient) PolicyInternetFirewallPublishPolicyRevision(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallPublishPolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallPublishPolicyRevision'
type BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call struct {
	*mock.Call
}

// PolicyInternetFirewallPublishPolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BulkInternetFirewallPolicyClient_Expecter) PolicyInternetFirewallPublishPolicyRevision(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyPublishRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	return &BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call{Call: _e.mock.On("PolicyInternetFirewallPublishPolicyRevision",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID}, interceptors...)...)}
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 *cato_models.PolicyPublishRevisionInput
		if args[2] != nil {
			arg2 = args[2].(*cato_models.PolicyPublishRevisionInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call) Return(policyInternetFirewallPublishPolicyRevision *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, err error) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Return(policyInternetFirewallPublishPolicyRevision, err)
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallReorderPolicy provides a mock function for the type BulkInternetFirewallPolicyClient
func (_mock *BulkInternetFirewallPolicyClient) PolicyInternetFirewallReorderPolicy(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallReorderPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallReorderPolicy")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallReorderPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallReorderPolicy, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallReorderPolicy); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallReorderPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallReorderPolicy'
type BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call struct {
	*mock.Call
}

// PolicyInternetFirewallReorderPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyReorderInput cato_models.PolicyReorderInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BulkInternetFirewallPolicyClient_Expecter) PolicyInternetFirewallReorderPolicy(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyReorderInput interface{}, accountID interface{}, interceptors ...interface{}) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call {
	return &BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call{Call: _e.mock.On("PolicyInternetFirewallReorderPolicy",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID}, interceptors...)...)}
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.PolicyReorderInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.PolicyReorderInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call) Return(policyInternetFirewallReorderPolicy *cato_go_sdk.PolicyInternetFirewallReorderPolicy, err error) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call {
	_c.Call.Return(policyInternetFirewallReorderPolicy, err)
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallReorderPolicy, error)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallReorderPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallRulesIndex provides a mock function for the type BulkInternetFirewallPolicyClient
func (_mock *BulkInternetFirewallPolicyClient) PolicyInternetFirewallRulesIndex(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.IfwRulesIndexPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallRulesIndex")
	}

	var r0 *cato_go_sdk.IfwRulesIndexPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.IfwRulesIndexPolicy, error)); ok {
		return returnFunc(ctx, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) *cato_go_sdk.IfwRulesIndexPolicy); ok {
		r0 = returnFunc(ctx, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.IfwRulesIndexPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallRulesIndex'
type BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call struct {
	*mock.Call
}

// PolicyInternetFirewallRulesIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BulkInternetFirewallPolicyClient_Expecter) PolicyInternetFirewallRulesIndex(ctx interface{}, accountID interface{}, interceptors ...interface{}) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call {
	return &BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call{Call: _e.mock.On("PolicyInternetFirewallRulesIndex",
		append([]interface{}{ctx, accountID}, interceptors...)...)}
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call) Run(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv2.RequestInterceptor)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call) Return(ifwRulesIndexPolicy *cato_go_sdk.IfwRulesIndexPolicy, err error) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call {
	_c.Call.Return(ifwRulesIndexPolicy, err)
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call) RunAndReturn(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.IfwRulesIndexPolicy, error)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallRulesIndex_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallSectionsIndex provides a mock function for the type BulkInternetFirewallPolicyClient
func (_mock *BulkInternetFirewallPolicyClient) PolicyInternetFirewallSectionsIndex(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.IfwSectionsIndexPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallSectionsIndex")
	}

	var r0 *cato_go_sdk.IfwSectionsIndexPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.IfwSectionsIndexPolicy, error)); ok {
		return returnFunc(ctx, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) *cato_go_sdk.IfwSectionsIndexPolicy); ok {
		r0 = returnFunc(ctx, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.IfwSectionsIndexPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallSectionsIndex'
type BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call struct {
	*mock.Call
}

// PolicyInternetFirewallSectionsIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BulkInternetFirewallPolicyClient_Expecter) PolicyInternetFirewallSectionsIndex(ctx interface{}, accountID interface{}, interceptors ...interface{}) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call {
	return &BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call{Call: _e.mock.On("PolicyInternetFirewallSectionsIndex",
		append([]interface{}{ctx, accountID}, interceptors...)...)}
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call) Run(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv2.RequestInterceptor)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call) Return(ifwSectionsIndexPolicy *cato_go_sdk.IfwSectionsIndexPolicy, err error) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call {
	_c.Call.Return(ifwSectionsIndexPolicy, err)
	return _c
}

func (_c *BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call) RunAndReturn(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.IfwSectionsIndexPolicy, error)) *BulkInternetFirewallPolicyClient_PolicyInternetFirewallSectionsIndex_Call {
	_c.Call.Return(run)
	return _c
}
