// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/Yamashou/gqlgenc/clientv2"
	"github.com/catonetworks/cato-go-sdk"
	"github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewBulkWanFirewallPolicyClient creates a new instance of BulkWanFirewallPolicyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBulkWanFirewallPolicyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BulkWanFirewallPolicyClient {
	mock := &BulkWanFirewallPolicyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BulkWanFirewallPolicyClient is an autogenerated mock type for the BulkWanFirewallPolicyClient type
type BulkWanFirewallPolicyClient struct {
	mock.Mock
}

type BulkWanFirewallPolicyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BulkWanFirewallPolicyClient) EXPECT() *BulkWanFirewallPolicyClient_Expecter {
	return &BulkWanFirewallPolicyClient_Expecter{mock: &_m.Mock}
}

// PolicyWanFirewallPublishPolicyRevision provides a mock function for the type BulkWanFirewallPolicyClient
func (_mock *BulkWanFirewallPolicyClient) PolicyWanFirewallPublishPolicyRevision(ctx context.Context, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, policyPublishRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, policyPublishRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallPublishPolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallPublishPolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, error)); ok {
		return returnFunc(ctx, policyPublishRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallPublishPolicyRevision); ok {
		r0 = returnFunc(ctx, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallPublishPolicyRevision'
type BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call struct {
	*mock.Call
}

// PolicyWanFirewallPublishPolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BulkWanFirewallPolicyClient_Expecter) PolicyWanFirewallPublishPolicyRevision(ctx interface{}, policyPublishRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call {
	return &BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call{Call: _e.mock.On("PolicyWanFirewallPublishPolicyRevision",
		append([]interface{}{ctx, policyPublishRevisionInput, accountID}, interceptors...)...)}
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call) Run(run func(ctx context.Context, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.PolicyPublishRevisionInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.PolicyPublishRevisionInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call) Return(policyWanFirewallPublishPolicyRevision *cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, err error) *BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call {
	_c.Call.Return(policyWanFirewallPublishPolicyRevision, err)
	return _c
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call) RunAndReturn(run func(ctx context.Context, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, error)) *BulkWanFirewallPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallReorderPolicy provides a mock function for the type BulkWanFirewallPolicyClient
func (_mock *BulkWanFirewallPolicyClient) PolicyWanFirewallReorderPolicy(ctx context.Context, wanFirewallPolicyMutationInput *cato_models.WanFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallReorderPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallReorderPolicy")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallReorderPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.WanFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallReorderPolicy, error)); ok {
		return returnFunc(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.WanFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallReorderPolicy); ok {
		r0 = returnFunc(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallReorderPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.WanFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallReorderPolicy'
type BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call struct {
	*mock.Call
}

// PolicyWanFirewallReorderPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - wanFirewallPolicyMutationInput *cato_models.WanFirewallPolicyMutationInput
//   - policyReorderInput cato_models.PolicyReorderInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BulkWanFirewallPolicyClient_Expecter) PolicyWanFirewallReorderPolicy(ctx interface{}, wanFirewallPolicyMutationInput interface{}, policyReorderInput interface{}, accountID interface{}, interceptors ...interface{}) *BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call {
	return &BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call{Call: _e.mock.On("PolicyWanFirewallReorderPolicy",
		append([]interface{}{ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID}, interceptors...)...)}
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call) Run(run func(ctx context.Context, wanFirewallPolicyMutationInput *cato_models.WanFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.WanFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.WanFirewallPolicyMutationInput)
		}
		var arg2 cato_models.PolicyReorderInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.PolicyReorderInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call) Return(policyWanFirewallReorderPolicy *cato_go_sdk.PolicyWanFirewallReorderPolicy, err error) *BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call {
	_c.Call.Return(policyWanFirewallReorderPolicy, err)
	return _c
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call) RunAndReturn(run func(ctx context.Context, wanFirewallPolicyMutationInput *cato_models.WanFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallReorderPolicy, error)) *BulkWanFirewallPolicyClient_PolicyWanFirewallReorderPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallRulesIndex provides a mock function for the type BulkWanFirewallPolicyClient
func (_mock *BulkWanFirewallPolicyClient) PolicyWanFirewallRulesIndex(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.WanRulesIndexPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallRulesIndex")
	}

	var r0 *cato_go_sdk.WanRulesIndexPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.WanRulesIndexPolicy, error)); ok {
		return returnFunc(ctx, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) *cato_go_sdk.WanRulesIndexPolicy); ok {
		r0 = returnFunc(ctx, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.WanRulesIndexPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallRulesIndex'
type BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call struct {
	*mock.Call
}

// PolicyWanFirewallRulesIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BulkWanFirewallPolicyClient_Expecter) PolicyWanFirewallRulesIndex(ctx interface{}, accountID interface{}, interceptors ...interface{}) *BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call {
	return &BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call{Call: _e.mock.On("PolicyWanFirewallRulesIndex",
		append([]interface{}{ctx, accountID}, interceptors...)...)}
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call) Run(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor)) *BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv2.RequestInterceptor)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call) Return(wanRulesIndexPolicy *cato_go_sdk.WanRulesIndexPolicy, err error) *BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call {
	_c.Call.Return(wanRulesIndexPolicy, err)
	return _c
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call) RunAndReturn(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.WanRulesIndexPolicy, error)) *BulkWanFirewallPolicyClient_PolicyWanFirewallRulesIndex_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallSectionsIndex provides a mock function for the type BulkWanFirewallPolicyClient
func (_mock *BulkWanFirewallPolicyClient) PolicyWanFirewallSectionsIndex(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.WanSectionsIndexPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallSectionsIndex")
	}

	var r0 *cato_go_sdk.WanSectionsIndexPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.WanSectionsIndexPolicy, error)); ok {
		return returnFunc(ctx, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) *cato_go_sdk.WanSectionsIndexPolicy); ok {
		r0 = returnFunc(ctx, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.WanSectionsIndexPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallSectionsIndex'
type BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call struct {
	*mock.Call
}

// PolicyWanFirewallSectionsIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *BulkWanFirewallPolicyClient_Expecter) PolicyWanFirewallSectionsIndex(ctx interface{}, accountID interface{}, interceptors ...interface{}) *BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call {
	return &BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call{Call: _e.mock.On("PolicyWanFirewallSectionsIndex",
		append([]interface{}{ctx, accountID}, interceptors...)...)}
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call) Run(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor)) *BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv2.RequestInterceptor)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call) Return(wanSectionsIndexPolicy *cato_go_sdk.WanSectionsIndexPolicy, err error) *BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call {
	_c.Call.Return(wanSectionsIndexPolicy, err)
	return _c
}

func (_c *BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call) RunAndReturn(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.WanSectionsIndexPolicy, error)) *BulkWanFirewallPolicyClient_PolicyWanFirewallSectionsIndex_Call {
	_c.Call.Return(run)
	return _c
}
