// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/Yamashou/gqlgenc/clientv2"
	"github.com/catonetworks/cato-go-sdk"
	"github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewIfwRulesIndexClient creates a new instance of IfwRulesIndexClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIfwRulesIndexClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IfwRulesIndexClient {
	mock := &IfwRulesIndexClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IfwRulesIndexClient is an autogenerated mock type for the IfwRulesIndexClient type
type IfwRulesIndexClient struct {
	mock.Mock
}

type IfwRulesIndexClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IfwRulesIndexClient) EXPECT() *IfwRulesIndexClient_Expecter {
	return &IfwRulesIndexClient_Expecter{mock: &_m.Mock}
}

// PolicyInternetFirewall provides a mock function for the type IfwRulesIndexClient
func (_mock *IfwRulesIndexClient) PolicyInternetFirewall(ctx context.Context, internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewall")
	}

	var r0 *cato_go_sdk.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.Policy); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IfwRulesIndexClient_PolicyInternetFirewall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewall'
type IfwRulesIndexClient_PolicyInternetFirewall_Call struct {
	*mock.Call
}

// PolicyInternetFirewall is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *IfwRulesIndexClient_Expecter) PolicyInternetFirewall(ctx interface{}, internetFirewallPolicyInput interface{}, accountID interface{}, interceptors ...interface{}) *IfwRulesIndexClient_PolicyInternetFirewall_Call {
	return &IfwRulesIndexClient_PolicyInternetFirewall_Call{Call: _e.mock.On("PolicyInternetFirewall",
		append([]interface{}{ctx, internetFirewallPolicyInput, accountID}, interceptors...)...)}
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewall_Call) Run(run func(ctx context.Context, internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *IfwRulesIndexClient_PolicyInternetFirewall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewall_Call) Return(policy *cato_go_sdk.Policy, err error) *IfwRulesIndexClient_PolicyInternetFirewall_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewall_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)) *IfwRulesIndexClient_PolicyInternetFirewall_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallAddSection provides a mock function for the type IfwRulesIndexClient
func (_mock *IfwRulesIndexClient) PolicyInternetFirewallAddSection(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyAddSectionInput cato_models.PolicyAddSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddSection, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallAddSection")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallAddSection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyAddSectionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddSection, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyAddSectionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallAddSection); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallAddSection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyAddSectionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallAddSection'
type IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call struct {
	*mock.Call
}

// PolicyInternetFirewallAddSection is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyAddSectionInput cato_models.PolicyAddSectionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *IfwRulesIndexClient_Expecter) PolicyInternetFirewallAddSection(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyAddSectionInput interface{}, accountID interface{}, interceptors ...interface{}) *IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call {
	return &IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call{Call: _e.mock.On("PolicyInternetFirewallAddSection",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyAddSectionInput, accountID}, interceptors...)...)}
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyAddSectionInput cato_models.PolicyAddSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.PolicyAddSectionInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.PolicyAddSectionInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call) Return(policyInternetFirewallAddSection *cato_go_sdk.PolicyInternetFirewallAddSection, err error) *IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call {
	_c.Call.Return(policyInternetFirewallAddSection, err)
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyAddSectionInput cato_models.PolicyAddSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddSection, error)) *IfwRulesIndexClient_PolicyInternetFirewallAddSection_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallCreatePolicyRevision provides a mock function for the type IfwRulesIndexClient
func (_mock *IfwRulesIndexClient) PolicyInternetFirewallCreatePolicyRevision(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyCreateRevisionInput cato_models.PolicyCreateRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallCreatePolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyCreateRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyCreateRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallCreatePolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallCreatePolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyCreateRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallCreatePolicyRevision, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyCreateRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyCreateRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallCreatePolicyRevision); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyCreateRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallCreatePolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyCreateRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyCreateRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallCreatePolicyRevision'
type IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call struct {
	*mock.Call
}

// PolicyInternetFirewallCreatePolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyCreateRevisionInput cato_models.PolicyCreateRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *IfwRulesIndexClient_Expecter) PolicyInternetFirewallCreatePolicyRevision(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyCreateRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call {
	return &IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call{Call: _e.mock.On("PolicyInternetFirewallCreatePolicyRevision",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyCreateRevisionInput, accountID}, interceptors...)...)}
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyCreateRevisionInput cato_models.PolicyCreateRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.PolicyCreateRevisionInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.PolicyCreateRevisionInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call) Return(policyInternetFirewallCreatePolicyRevision *cato_go_sdk.PolicyInternetFirewallCreatePolicyRevision, err error) *IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call {
	_c.Call.Return(policyInternetFirewallCreatePolicyRevision, err)
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyCreateRevisionInput cato_models.PolicyCreateRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallCreatePolicyRevision, error)) *IfwRulesIndexClient_PolicyInternetFirewallCreatePolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallMoveSection provides a mock function for the type IfwRulesIndexClient
func (_mock *IfwRulesIndexClient) PolicyInternetFirewallMoveSection(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyMoveSectionInput cato_models.PolicyMoveSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallMoveSection, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyMoveSectionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyMoveSectionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallMoveSection")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallMoveSection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyMoveSectionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallMoveSection, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyMoveSectionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyMoveSectionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallMoveSection); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyMoveSectionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallMoveSection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyMoveSectionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyMoveSectionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallMoveSection'
type IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call struct {
	*mock.Call
}

// PolicyInternetFirewallMoveSection is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyMoveSectionInput cato_models.PolicyMoveSectionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *IfwRulesIndexClient_Expecter) PolicyInternetFirewallMoveSection(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyMoveSectionInput interface{}, accountID interface{}, interceptors ...interface{}) *IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call {
	return &IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call{Call: _e.mock.On("PolicyInternetFirewallMoveSection",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyMoveSectionInput, accountID}, interceptors...)...)}
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyMoveSectionInput cato_models.PolicyMoveSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.PolicyMoveSectionInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.PolicyMoveSectionInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call) Return(policyInternetFirewallMoveSection *cato_go_sdk.PolicyInternetFirewallMoveSection, err error) *IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call {
	_c.Call.Return(policyInternetFirewallMoveSection, err)
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyMoveSectionInput cato_models.PolicyMoveSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallMoveSection, error)) *IfwRulesIndexClient_PolicyInternetFirewallMoveSection_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallPublishPolicyRevision provides a mock function for the type IfwRulesIndexClient
func (_mock *IfwRulesIndexClient) PolicyInternetFirewallPublishPolicyRevision(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallPublishPolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallPublishPolicyRevision'
type IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call struct {
	*mock.Call
}

// PolicyInternetFirewallPublishPolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *IfwRulesIndexClient_Expecter) PolicyInternetFirewallPublishPolicyRevision(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyPublishRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	return &IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call{Call: _e.mock.On("PolicyInternetFirewallPublishPolicyRevision",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID}, interceptors...)...)}
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 *cato_models.PolicyPublishRevisionInput
		if args[2] != nil {
			arg2 = args[2].(*cato_models.PolicyPublishRevisionInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call) Return(policyInternetFirewallPublishPolicyRevision *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, err error) *IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Return(policyInternetFirewallPublishPolicyRevision, err)
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error)) *IfwRulesIndexClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallReorderPolicy provides a mock function for the type IfwRulesIndexClient
func (_mock *IfwRulesIndexClient) PolicyInternetFirewallReorderPolicy(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallReorderPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallReorderPolicy")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallReorderPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallReorderPolicy, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallReorderPolicy); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallReorderPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallReorderPolicy'
type IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call struct {
	*mock.Call
}

// PolicyInternetFirewallReorderPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyReorderInput cato_models.PolicyReorderInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *IfwRulesIndexClient_Expecter) PolicyInternetFirewallReorderPolicy(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyReorderInput interface{}, accountID interface{}, interceptors ...interface{}) *IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call {
	return &IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call{Call: _e.mock.On("PolicyInternetFirewallReorderPolicy",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyReorderInput, accountID}, interceptors...)...)}
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.PolicyReorderInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.PolicyReorderInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call) Return(policyInternetFirewallReorderPolicy *cato_go_sdk.PolicyInternetFirewallReorderPolicy, err error) *IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call {
	_c.Call.Return(policyInternetFirewallReorderPolicy, err)
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallReorderPolicy, error)) *IfwRulesIndexClient_PolicyInternetFirewallReorderPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallSectionsIndex provides a mock function for the type IfwRulesIndexClient
func (_mock *IfwRulesIndexClient) PolicyInternetFirewallSectionsIndex(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.IfwSectionsIndexPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallSectionsIndex")
	}

	var r0 *cato_go_sdk.IfwSectionsIndexPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.IfwSectionsIndexPolicy, error)); ok {
		return returnFunc(ctx, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) *cato_go_sdk.IfwSectionsIndexPolicy); ok {
		r0 = returnFunc(ctx, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.IfwSectionsIndexPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallSectionsIndex'
type IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call struct {
	*mock.Call
}

// PolicyInternetFirewallSectionsIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *IfwRulesIndexClient_Expecter) PolicyInternetFirewallSectionsIndex(ctx interface{}, accountID interface{}, interceptors ...interface{}) *IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call {
	return &IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call{Call: _e.mock.On("PolicyInternetFirewallSectionsIndex",
		append([]interface{}{ctx, accountID}, interceptors...)...)}
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call) Run(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor)) *IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv2.RequestInterceptor)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call) Return(ifwSectionsIndexPolicy *cato_go_sdk.IfwSectionsIndexPolicy, err error) *IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call {
	_c.Call.Return(ifwSectionsIndexPolicy, err)
	return _c
}

func (_c *IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call) RunAndReturn(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.IfwSectionsIndexPolicy, error)) *IfwRulesIndexClient_PolicyInternetFirewallSectionsIndex_Call {
	_c.Call.Return(run)
	return _c
}
