// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/Yamashou/gqlgenc/clientv2"
	"github.com/catonetworks/cato-go-sdk"
	"github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewInternetFirewallPolicyClient creates a new instance of InternetFirewallPolicyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternetFirewallPolicyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternetFirewallPolicyClient {
	mock := &InternetFirewallPolicyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InternetFirewallPolicyClient is an autogenerated mock type for the InternetFirewallPolicyClient type
type InternetFirewallPolicyClient struct {
	mock.Mock
}

type InternetFirewallPolicyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InternetFirewallPolicyClient) EXPECT() *InternetFirewallPolicyClient_Expecter {
	return &InternetFirewallPolicyClient_Expecter{mock: &_m.Mock}
}

// PolicyInternetFirewall provides a mock function for the type InternetFirewallPolicyClient
func (_mock *InternetFirewallPolicyClient) PolicyInternetFirewall(ctx context.Context, internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewall")
	}

	var r0 *cato_go_sdk.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.Policy); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallPolicyClient_PolicyInternetFirewall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewall'
type InternetFirewallPolicyClient_PolicyInternetFirewall_Call struct {
	*mock.Call
}

// PolicyInternetFirewall is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallPolicyClient_Expecter) PolicyInternetFirewall(ctx interface{}, internetFirewallPolicyInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallPolicyClient_PolicyInternetFirewall_Call {
	return &InternetFirewallPolicyClient_PolicyInternetFirewall_Call{Call: _e.mock.On("PolicyInternetFirewall",
		append([]interface{}{ctx, internetFirewallPolicyInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewall_Call) Run(run func(ctx context.Context, internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallPolicyClient_PolicyInternetFirewall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewall_Call) Return(policy *cato_go_sdk.Policy, err error) *InternetFirewallPolicyClient_PolicyInternetFirewall_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewall_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)) *InternetFirewallPolicyClient_PolicyInternetFirewall_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallAddRule provides a mock function for the type InternetFirewallPolicyClient
func (_mock *InternetFirewallPolicyClient) PolicyInternetFirewallAddRule(ctx context.Context, internetFirewallAddRuleInput cato_models.InternetFirewallAddRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddRule, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallAddRuleInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallAddRuleInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallAddRule")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallAddRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.InternetFirewallAddRuleInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddRule, error)); ok {
		return returnFunc(ctx, internetFirewallAddRuleInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.InternetFirewallAddRuleInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallAddRule); ok {
		r0 = returnFunc(ctx, internetFirewallAddRuleInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallAddRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.InternetFirewallAddRuleInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallAddRuleInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallAddRule'
type InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call struct {
	*mock.Call
}

// PolicyInternetFirewallAddRule is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallAddRuleInput cato_models.InternetFirewallAddRuleInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallPolicyClient_Expecter) PolicyInternetFirewallAddRule(ctx interface{}, internetFirewallAddRuleInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call {
	return &InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call{Call: _e.mock.On("PolicyInternetFirewallAddRule",
		append([]interface{}{ctx, internetFirewallAddRuleInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call) Run(run func(ctx context.Context, internetFirewallAddRuleInput cato_models.InternetFirewallAddRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.InternetFirewallAddRuleInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.InternetFirewallAddRuleInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call) Return(policyInternetFirewallAddRule *cato_go_sdk.PolicyInternetFirewallAddRule, err error) *InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call {
	_c.Call.Return(policyInternetFirewallAddRule, err)
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call) RunAndReturn(run func(ctx context.Context, internetFirewallAddRuleInput cato_models.InternetFirewallAddRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddRule, error)) *InternetFirewallPolicyClient_PolicyInternetFirewallAddRule_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallMoveRule provides a mock function for the type InternetFirewallPolicyClient
func (_mock *InternetFirewallPolicyClient) PolicyInternetFirewallMoveRule(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyMoveRuleInput cato_models.PolicyMoveRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallMoveRule, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyMoveRuleInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyMoveRuleInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallMoveRule")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallMoveRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyMoveRuleInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallMoveRule, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyMoveRuleInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyMoveRuleInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallMoveRule); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyMoveRuleInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallMoveRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.PolicyMoveRuleInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyMoveRuleInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallMoveRule'
type InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call struct {
	*mock.Call
}

// PolicyInternetFirewallMoveRule is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyMoveRuleInput cato_models.PolicyMoveRuleInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallPolicyClient_Expecter) PolicyInternetFirewallMoveRule(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyMoveRuleInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call {
	return &InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call{Call: _e.mock.On("PolicyInternetFirewallMoveRule",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyMoveRuleInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyMoveRuleInput cato_models.PolicyMoveRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.PolicyMoveRuleInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.PolicyMoveRuleInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call) Return(policyInternetFirewallMoveRule *cato_go_sdk.PolicyInternetFirewallMoveRule, err error) *InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call {
	_c.Call.Return(policyInternetFirewallMoveRule, err)
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyMoveRuleInput cato_models.PolicyMoveRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallMoveRule, error)) *InternetFirewallPolicyClient_PolicyInternetFirewallMoveRule_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallPublishPolicyRevision provides a mock function for the type InternetFirewallPolicyClient
func (_mock *InternetFirewallPolicyClient) PolicyInternetFirewallPublishPolicyRevision(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallPublishPolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallPublishPolicyRevision'
type InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call struct {
	*mock.Call
}

// PolicyInternetFirewallPublishPolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallPolicyClient_Expecter) PolicyInternetFirewallPublishPolicyRevision(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyPublishRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	return &InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call{Call: _e.mock.On("PolicyInternetFirewallPublishPolicyRevision",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 *cato_models.PolicyPublishRevisionInput
		if args[2] != nil {
			arg2 = args[2].(*cato_models.PolicyPublishRevisionInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call) Return(policyInternetFirewallPublishPolicyRevision *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, err error) *InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Return(policyInternetFirewallPublishPolicyRevision, err)
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error)) *InternetFirewallPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallRemoveRule provides a mock function for the type InternetFirewallPolicyClient
func (_mock *InternetFirewallPolicyClient) PolicyInternetFirewallRemoveRule(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallRemoveRuleInput cato_models.InternetFirewallRemoveRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallRemoveRule, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveRuleInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveRuleInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallRemoveRule")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallRemoveRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallRemoveRuleInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallRemoveRule, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveRuleInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallRemoveRuleInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallRemoveRule); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveRuleInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallRemoveRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallRemoveRuleInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveRuleInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallRemoveRule'
type InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call struct {
	*mock.Call
}

// PolicyInternetFirewallRemoveRule is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - internetFirewallRemoveRuleInput cato_models.InternetFirewallRemoveRuleInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallPolicyClient_Expecter) PolicyInternetFirewallRemoveRule(ctx interface{}, internetFirewallPolicyMutationInput interface{}, internetFirewallRemoveRuleInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call {
	return &InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call{Call: _e.mock.On("PolicyInternetFirewallRemoveRule",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveRuleInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallRemoveRuleInput cato_models.InternetFirewallRemoveRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.InternetFirewallRemoveRuleInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.InternetFirewallRemoveRuleInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call) Return(policyInternetFirewallRemoveRule *cato_go_sdk.PolicyInternetFirewallRemoveRule, err error) *InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call {
	_c.Call.Return(policyInternetFirewallRemoveRule, err)
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallRemoveRuleInput cato_models.InternetFirewallRemoveRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallRemoveRule, error)) *InternetFirewallPolicyClient_PolicyInternetFirewallRemoveRule_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallUpdateRule provides a mock function for the type InternetFirewallPolicyClient
func (_mock *InternetFirewallPolicyClient) PolicyInternetFirewallUpdateRule(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput cato_models.InternetFirewallUpdateRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallUpdateRule, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallUpdateRule")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallUpdateRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallUpdateRuleInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallUpdateRule, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallUpdateRuleInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallUpdateRule); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallUpdateRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallUpdateRuleInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallUpdateRule'
type InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call struct {
	*mock.Call
}

// PolicyInternetFirewallUpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - internetFirewallUpdateRuleInput cato_models.InternetFirewallUpdateRuleInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallPolicyClient_Expecter) PolicyInternetFirewallUpdateRule(ctx interface{}, internetFirewallPolicyMutationInput interface{}, internetFirewallUpdateRuleInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call {
	return &InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call{Call: _e.mock.On("PolicyInternetFirewallUpdateRule",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput cato_models.InternetFirewallUpdateRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.InternetFirewallUpdateRuleInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.InternetFirewallUpdateRuleInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call) Return(policyInternetFirewallUpdateRule *cato_go_sdk.PolicyInternetFirewallUpdateRule, err error) *InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call {
	_c.Call.Return(policyInternetFirewallUpdateRule, err)
	return _c
}

func (_c *InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput cato_models.InternetFirewallUpdateRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallUpdateRule, error)) *InternetFirewallPolicyClient_PolicyInternetFirewallUpdateRule_Call {
	_c.Call.Return(run)
	return _c
}
