// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Yamashou/gqlgenc/clientv2"
	cato_go_sdk "github.com/catonetworks/cato-go-sdk"
	cato_models "github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewInternetFirewallSubPolicyClient creates a new instance of InternetFirewallSubPolicyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternetFirewallSubPolicyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternetFirewallSubPolicyClient {
	mock := &InternetFirewallSubPolicyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InternetFirewallSubPolicyClient is an autogenerated mock type for the InternetFirewallSubPolicyClient type
type InternetFirewallSubPolicyClient struct {
	mock.Mock
}

type InternetFirewallSubPolicyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InternetFirewallSubPolicyClient) EXPECT() *InternetFirewallSubPolicyClient_Expecter {
	return &InternetFirewallSubPolicyClient_Expecter{mock: &_m.Mock}
}

// PolicyInternetFirewall provides a mock function for the type InternetFirewallSubPolicyClient
func (_mock *InternetFirewallSubPolicyClient) PolicyInternetFirewall(ctx context.Context, internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewall")
	}

	var r0 *cato_go_sdk.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.Policy); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewall'
type InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call struct {
	*mock.Call
}

// PolicyInternetFirewall is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallSubPolicyClient_Expecter) PolicyInternetFirewall(ctx interface{}, internetFirewallPolicyInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call {
	return &InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call{Call: _e.mock.On("PolicyInternetFirewall",
		append([]interface{}{ctx, internetFirewallPolicyInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call) Run(run func(ctx context.Context, internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call) Return(policy *cato_go_sdk.Policy, err error) *InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyInput *cato_models.InternetFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)) *InternetFirewallSubPolicyClient_PolicyInternetFirewall_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallAddSubPolicy provides a mock function for the type InternetFirewallSubPolicyClient
func (_mock *InternetFirewallSubPolicyClient) PolicyInternetFirewallAddSubPolicy(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallAddSubPolicyInput cato_models.InternetFirewallAddSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddSubPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallAddSubPolicyInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallAddSubPolicyInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallAddSubPolicy")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallAddSubPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallAddSubPolicyInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddSubPolicy, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallAddSubPolicyInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallAddSubPolicyInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallAddSubPolicy); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallAddSubPolicyInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallAddSubPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallAddSubPolicyInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallAddSubPolicyInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallAddSubPolicy'
type InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call struct {
	*mock.Call
}

// PolicyInternetFirewallAddSubPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - internetFirewallAddSubPolicyInput cato_models.InternetFirewallAddSubPolicyInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallSubPolicyClient_Expecter) PolicyInternetFirewallAddSubPolicy(ctx interface{}, internetFirewallPolicyMutationInput interface{}, internetFirewallAddSubPolicyInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call {
	return &InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call{Call: _e.mock.On("PolicyInternetFirewallAddSubPolicy",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, internetFirewallAddSubPolicyInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallAddSubPolicyInput cato_models.InternetFirewallAddSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.InternetFirewallAddSubPolicyInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.InternetFirewallAddSubPolicyInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call) Return(policyInternetFirewallAddSubPolicy *cato_go_sdk.PolicyInternetFirewallAddSubPolicy, err error) *InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call {
	_c.Call.Return(policyInternetFirewallAddSubPolicy, err)
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallAddSubPolicyInput cato_models.InternetFirewallAddSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallAddSubPolicy, error)) *InternetFirewallSubPolicyClient_PolicyInternetFirewallAddSubPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallPublishPolicyRevision provides a mock function for the type InternetFirewallSubPolicyClient
func (_mock *InternetFirewallSubPolicyClient) PolicyInternetFirewallPublishPolicyRevision(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallPublishPolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallPublishPolicyRevision'
type InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call struct {
	*mock.Call
}

// PolicyInternetFirewallPublishPolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallSubPolicyClient_Expecter) PolicyInternetFirewallPublishPolicyRevision(ctx interface{}, internetFirewallPolicyMutationInput interface{}, policyPublishRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	return &InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call{Call: _e.mock.On("PolicyInternetFirewallPublishPolicyRevision",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, policyPublishRevisionInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 *cato_models.PolicyPublishRevisionInput
		if args[2] != nil {
			arg2 = args[2].(*cato_models.PolicyPublishRevisionInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call) Return(policyInternetFirewallPublishPolicyRevision *cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, err error) *InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Return(policyInternetFirewallPublishPolicyRevision, err)
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallPublishPolicyRevision, error)) *InternetFirewallSubPolicyClient_PolicyInternetFirewallPublishPolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallRemoveSubPolicy provides a mock function for the type InternetFirewallSubPolicyClient
func (_mock *InternetFirewallSubPolicyClient) PolicyInternetFirewallRemoveSubPolicy(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallRemoveSubPolicyInput cato_models.InternetFirewallRemoveSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallRemoveSubPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveSubPolicyInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveSubPolicyInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallRemoveSubPolicy")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallRemoveSubPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallRemoveSubPolicyInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallRemoveSubPolicy, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveSubPolicyInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallRemoveSubPolicyInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallRemoveSubPolicy); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveSubPolicyInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallRemoveSubPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallRemoveSubPolicyInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveSubPolicyInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallRemoveSubPolicy'
type InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call struct {
	*mock.Call
}

// PolicyInternetFirewallRemoveSubPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - internetFirewallRemoveSubPolicyInput cato_models.InternetFirewallRemoveSubPolicyInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallSubPolicyClient_Expecter) PolicyInternetFirewallRemoveSubPolicy(ctx interface{}, internetFirewallPolicyMutationInput interface{}, internetFirewallRemoveSubPolicyInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call {
	return &InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call{Call: _e.mock.On("PolicyInternetFirewallRemoveSubPolicy",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, internetFirewallRemoveSubPolicyInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallRemoveSubPolicyInput cato_models.InternetFirewallRemoveSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.InternetFirewallRemoveSubPolicyInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.InternetFirewallRemoveSubPolicyInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call) Return(policyInternetFirewallRemoveSubPolicy *cato_go_sdk.PolicyInternetFirewallRemoveSubPolicy, err error) *InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call {
	_c.Call.Return(policyInternetFirewallRemoveSubPolicy, err)
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallRemoveSubPolicyInput cato_models.InternetFirewallRemoveSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallRemoveSubPolicy, error)) *InternetFirewallSubPolicyClient_PolicyInternetFirewallRemoveSubPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyInternetFirewallUpdateRule provides a mock function for the type InternetFirewallSubPolicyClient
func (_mock *InternetFirewallSubPolicyClient) PolicyInternetFirewallUpdateRule(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput cato_models.InternetFirewallUpdateRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallUpdateRule, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyInternetFirewallUpdateRule")
	}

	var r0 *cato_go_sdk.PolicyInternetFirewallUpdateRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallUpdateRuleInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallUpdateRule, error)); ok {
		return returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallUpdateRuleInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyInternetFirewallUpdateRule); ok {
		r0 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyInternetFirewallUpdateRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.InternetFirewallPolicyMutationInput, cato_models.InternetFirewallUpdateRuleInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyInternetFirewallUpdateRule'
type InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call struct {
	*mock.Call
}

// PolicyInternetFirewallUpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput
//   - internetFirewallUpdateRuleInput cato_models.InternetFirewallUpdateRuleInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *InternetFirewallSubPolicyClient_Expecter) PolicyInternetFirewallUpdateRule(ctx interface{}, internetFirewallPolicyMutationInput interface{}, internetFirewallUpdateRuleInput interface{}, accountID interface{}, interceptors ...interface{}) *InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call {
	return &InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call{Call: _e.mock.On("PolicyInternetFirewallUpdateRule",
		append([]interface{}{ctx, internetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput, accountID}, interceptors...)...)}
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call) Run(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput cato_models.InternetFirewallUpdateRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.InternetFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.InternetFirewallPolicyMutationInput)
		}
		var arg2 cato_models.InternetFirewallUpdateRuleInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.InternetFirewallUpdateRuleInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call) Return(policyInternetFirewallUpdateRule *cato_go_sdk.PolicyInternetFirewallUpdateRule, err error) *InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call {
	_c.Call.Return(policyInternetFirewallUpdateRule, err)
	return _c
}

func (_c *InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call) RunAndReturn(run func(ctx context.Context, internetFirewallPolicyMutationInput *cato_models.InternetFirewallPolicyMutationInput, internetFirewallUpdateRuleInput cato_models.InternetFirewallUpdateRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyInternetFirewallUpdateRule, error)) *InternetFirewallSubPolicyClient_PolicyInternetFirewallUpdateRule_Call {
	_c.Call.Return(run)
	return _c
}
