// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/catonetworks/terraform-provider-cato/internal/provider/network/netrange/application"
)

// NewNetworkRangePort creates a new instance of NetworkRangePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetworkRangePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetworkRangePort {
	mock := &NetworkRangePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NetworkRangePort is an autogenerated mock type for the NetworkRangePort type
type NetworkRangePort struct {
	mock.Mock
}

type NetworkRangePort_Expecter struct {
	mock *mock.Mock
}

func (_m *NetworkRangePort) EXPECT() *NetworkRangePort_Expecter {
	return &NetworkRangePort_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type NetworkRangePort
func (_mock *NetworkRangePort) Add(context1 context.Context, s string, input application.Input) (string, error) {
	ret := _mock.Called(context1, s, input)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, application.Input) (string, error)); ok {
		return returnFunc(context1, s, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, application.Input) string); ok {
		r0 = returnFunc(context1, s, input)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, application.Input) error); ok {
		r1 = returnFunc(context1, s, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangePort_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type NetworkRangePort_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - input application.Input
func (_e *NetworkRangePort_Expecter) Add(context1 interface{}, s interface{}, input interface{}) *NetworkRangePort_Add_Call {
	return &NetworkRangePort_Add_Call{Call: _e.mock.On("Add", context1, s, input)}
}

func (_c *NetworkRangePort_Add_Call) Run(run func(context1 context.Context, s string, input application.Input)) *NetworkRangePort_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 application.Input
		if args[2] != nil {
			arg2 = args[2].(application.Input)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NetworkRangePort_Add_Call) Return(s1 string, err error) *NetworkRangePort_Add_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *NetworkRangePort_Add_Call) RunAndReturn(run func(context1 context.Context, s string, input application.Input) (string, error)) *NetworkRangePort_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type NetworkRangePort
func (_mock *NetworkRangePort) Fetch(context1 context.Context, s string) (*application.Snapshot, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *application.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*application.Snapshot, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *application.Snapshot); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangePort_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type NetworkRangePort_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *NetworkRangePort_Expecter) Fetch(context1 interface{}, s interface{}) *NetworkRangePort_Fetch_Call {
	return &NetworkRangePort_Fetch_Call{Call: _e.mock.On("Fetch", context1, s)}
}

func (_c *NetworkRangePort_Fetch_Call) Run(run func(context1 context.Context, s string)) *NetworkRangePort_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NetworkRangePort_Fetch_Call) Return(snapshot *application.Snapshot, err error) *NetworkRangePort_Fetch_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *NetworkRangePort_Fetch_Call) RunAndReturn(run func(context1 context.Context, s string) (*application.Snapshot, error)) *NetworkRangePort_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// InterfaceID provides a mock function for the type NetworkRangePort
func (_mock *NetworkRangePort) InterfaceID(context1 context.Context, s string, s1 string) (string, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for InterfaceID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangePort_InterfaceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InterfaceID'
type NetworkRangePort_InterfaceID_Call struct {
	*mock.Call
}

// InterfaceID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *NetworkRangePort_Expecter) InterfaceID(context1 interface{}, s interface{}, s1 interface{}) *NetworkRangePort_InterfaceID_Call {
	return &NetworkRangePort_InterfaceID_Call{Call: _e.mock.On("InterfaceID", context1, s, s1)}
}

func (_c *NetworkRangePort_InterfaceID_Call) Run(run func(context1 context.Context, s string, s1 string)) *NetworkRangePort_InterfaceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NetworkRangePort_InterfaceID_Call) Return(s2 string, err error) *NetworkRangePort_InterfaceID_Call {
	_c.Call.Return(s2, err)
	return _c
}

func (_c *NetworkRangePort_InterfaceID_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (string, error)) *NetworkRangePort_InterfaceID_Call {
	_c.Call.Return(run)
	return _c
}

// InterfaceIndex provides a mock function for the type NetworkRangePort
func (_mock *NetworkRangePort) InterfaceIndex(context1 context.Context, s string, s1 string) (string, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for InterfaceIndex")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangePort_InterfaceIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InterfaceIndex'
type NetworkRangePort_InterfaceIndex_Call struct {
	*mock.Call
}

// InterfaceIndex is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *NetworkRangePort_Expecter) InterfaceIndex(context1 interface{}, s interface{}, s1 interface{}) *NetworkRangePort_InterfaceIndex_Call {
	return &NetworkRangePort_InterfaceIndex_Call{Call: _e.mock.On("InterfaceIndex", context1, s, s1)}
}

func (_c *NetworkRangePort_InterfaceIndex_Call) Run(run func(context1 context.Context, s string, s1 string)) *NetworkRangePort_InterfaceIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NetworkRangePort_InterfaceIndex_Call) Return(s2 string, err error) *NetworkRangePort_InterfaceIndex_Call {
	_c.Call.Return(s2, err)
	return _c
}

func (_c *NetworkRangePort_InterfaceIndex_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (string, error)) *NetworkRangePort_InterfaceIndex_Call {
	_c.Call.Return(run)
	return _c
}

// RelayID provides a mock function for the type NetworkRangePort
func (_mock *NetworkRangePort) RelayID(context1 context.Context, s string) (string, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RelayID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangePort_RelayID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RelayID'
type NetworkRangePort_RelayID_Call struct {
	*mock.Call
}

// RelayID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *NetworkRangePort_Expecter) RelayID(context1 interface{}, s interface{}) *NetworkRangePort_RelayID_Call {
	return &NetworkRangePort_RelayID_Call{Call: _e.mock.On("RelayID", context1, s)}
}

func (_c *NetworkRangePort_RelayID_Call) Run(run func(context1 context.Context, s string)) *NetworkRangePort_RelayID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NetworkRangePort_RelayID_Call) Return(s1 string, err error) *NetworkRangePort_RelayID_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *NetworkRangePort_RelayID_Call) RunAndReturn(run func(context1 context.Context, s string) (string, error)) *NetworkRangePort_RelayID_Call {
	_c.Call.Return(run)
	return _c
}

// RelayName provides a mock function for the type NetworkRangePort
func (_mock *NetworkRangePort) RelayName(context1 context.Context, s string) (*string, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RelayName")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangePort_RelayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RelayName'
type NetworkRangePort_RelayName_Call struct {
	*mock.Call
}

// RelayName is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *NetworkRangePort_Expecter) RelayName(context1 interface{}, s interface{}) *NetworkRangePort_RelayName_Call {
	return &NetworkRangePort_RelayName_Call{Call: _e.mock.On("RelayName", context1, s)}
}

func (_c *NetworkRangePort_RelayName_Call) Run(run func(context1 context.Context, s string)) *NetworkRangePort_RelayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NetworkRangePort_RelayName_Call) Return(s1 *string, err error) *NetworkRangePort_RelayName_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *NetworkRangePort_RelayName_Call) RunAndReturn(run func(context1 context.Context, s string) (*string, error)) *NetworkRangePort_RelayName_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type NetworkRangePort
func (_mock *NetworkRangePort) Remove(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NetworkRangePort_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type NetworkRangePort_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *NetworkRangePort_Expecter) Remove(context1 interface{}, s interface{}) *NetworkRangePort_Remove_Call {
	return &NetworkRangePort_Remove_Call{Call: _e.mock.On("Remove", context1, s)}
}

func (_c *NetworkRangePort_Remove_Call) Run(run func(context1 context.Context, s string)) *NetworkRangePort_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NetworkRangePort_Remove_Call) Return(err error) *NetworkRangePort_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NetworkRangePort_Remove_Call) RunAndReturn(run func(context1 context.Context, s string) error) *NetworkRangePort_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type NetworkRangePort
func (_mock *NetworkRangePort) Update(context1 context.Context, input application.Input) error {
	ret := _mock.Called(context1, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.Input) error); ok {
		r0 = returnFunc(context1, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NetworkRangePort_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type NetworkRangePort_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - input application.Input
func (_e *NetworkRangePort_Expecter) Update(context1 interface{}, input interface{}) *NetworkRangePort_Update_Call {
	return &NetworkRangePort_Update_Call{Call: _e.mock.On("Update", context1, input)}
}

func (_c *NetworkRangePort_Update_Call) Run(run func(context1 context.Context, input application.Input)) *NetworkRangePort_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.Input
		if args[1] != nil {
			arg1 = args[1].(application.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NetworkRangePort_Update_Call) Return(err error) *NetworkRangePort_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NetworkRangePort_Update_Call) RunAndReturn(run func(context1 context.Context, input application.Input) error) *NetworkRangePort_Update_Call {
	_c.Call.Return(run)
	return _c
}
