// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Yamashou/gqlgenc/clientv2"
	cato_go_sdk "github.com/catonetworks/cato-go-sdk"
	cato_models "github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewNetworkRangeClient creates a new instance of NetworkRangeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetworkRangeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetworkRangeClient {
	mock := &NetworkRangeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NetworkRangeClient is an autogenerated mock type for the NetworkRangeClient type
type NetworkRangeClient struct {
	mock.Mock
}

type NetworkRangeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *NetworkRangeClient) EXPECT() *NetworkRangeClient_Expecter {
	return &NetworkRangeClient_Expecter{mock: &_m.Mock}
}

// EntityLookup provides a mock function for the type NetworkRangeClient
func (_mock *NetworkRangeClient) EntityLookup(context1 context.Context, s string, entityType cato_models.EntityType, n *int64, n1 *int64, entityInput *cato_models.EntityInput, s1 *string, strings []string, sortInputs []*cato_models.SortInput, lookupFilterInputs []*cato_models.LookupFilterInput, strings1 []string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.EntityLookup, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, entityType, n, n1, entityInput, s1, strings, sortInputs, lookupFilterInputs, strings1, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, entityType, n, n1, entityInput, s1, strings, sortInputs, lookupFilterInputs, strings1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EntityLookup")
	}

	var r0 *cato_go_sdk.EntityLookup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.EntityType, *int64, *int64, *cato_models.EntityInput, *string, []string, []*cato_models.SortInput, []*cato_models.LookupFilterInput, []string, ...clientv2.RequestInterceptor) (*cato_go_sdk.EntityLookup, error)); ok {
		return returnFunc(context1, s, entityType, n, n1, entityInput, s1, strings, sortInputs, lookupFilterInputs, strings1, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.EntityType, *int64, *int64, *cato_models.EntityInput, *string, []string, []*cato_models.SortInput, []*cato_models.LookupFilterInput, []string, ...clientv2.RequestInterceptor) *cato_go_sdk.EntityLookup); ok {
		r0 = returnFunc(context1, s, entityType, n, n1, entityInput, s1, strings, sortInputs, lookupFilterInputs, strings1, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.EntityLookup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cato_models.EntityType, *int64, *int64, *cato_models.EntityInput, *string, []string, []*cato_models.SortInput, []*cato_models.LookupFilterInput, []string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, entityType, n, n1, entityInput, s1, strings, sortInputs, lookupFilterInputs, strings1, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangeClient_EntityLookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EntityLookup'
type NetworkRangeClient_EntityLookup_Call struct {
	*mock.Call
}

// EntityLookup is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - entityType cato_models.EntityType
//   - n *int64
//   - n1 *int64
//   - entityInput *cato_models.EntityInput
//   - s1 *string
//   - strings []string
//   - sortInputs []*cato_models.SortInput
//   - lookupFilterInputs []*cato_models.LookupFilterInput
//   - strings1 []string
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *NetworkRangeClient_Expecter) EntityLookup(context1 interface{}, s interface{}, entityType interface{}, n interface{}, n1 interface{}, entityInput interface{}, s1 interface{}, strings interface{}, sortInputs interface{}, lookupFilterInputs interface{}, strings1 interface{}, requestInterceptors ...interface{}) *NetworkRangeClient_EntityLookup_Call {
	return &NetworkRangeClient_EntityLookup_Call{Call: _e.mock.On("EntityLookup",
		append([]interface{}{context1, s, entityType, n, n1, entityInput, s1, strings, sortInputs, lookupFilterInputs, strings1}, requestInterceptors...)...)}
}

func (_c *NetworkRangeClient_EntityLookup_Call) Run(run func(context1 context.Context, s string, entityType cato_models.EntityType, n *int64, n1 *int64, entityInput *cato_models.EntityInput, s1 *string, strings []string, sortInputs []*cato_models.SortInput, lookupFilterInputs []*cato_models.LookupFilterInput, strings1 []string, requestInterceptors ...clientv2.RequestInterceptor)) *NetworkRangeClient_EntityLookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cato_models.EntityType
		if args[2] != nil {
			arg2 = args[2].(cato_models.EntityType)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 *cato_models.EntityInput
		if args[5] != nil {
			arg5 = args[5].(*cato_models.EntityInput)
		}
		var arg6 *string
		if args[6] != nil {
			arg6 = args[6].(*string)
		}
		var arg7 []string
		if args[7] != nil {
			arg7 = args[7].([]string)
		}
		var arg8 []*cato_models.SortInput
		if args[8] != nil {
			arg8 = args[8].([]*cato_models.SortInput)
		}
		var arg9 []*cato_models.LookupFilterInput
		if args[9] != nil {
			arg9 = args[9].([]*cato_models.LookupFilterInput)
		}
		var arg10 []string
		if args[10] != nil {
			arg10 = args[10].([]string)
		}
		var arg11 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 11 {
			variadicArgs = args[11].([]clientv2.RequestInterceptor)
		}
		arg11 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
			arg9,
			arg10,
			arg11...,
		)
	})
	return _c
}

func (_c *NetworkRangeClient_EntityLookup_Call) Return(entityLookup *cato_go_sdk.EntityLookup, err error) *NetworkRangeClient_EntityLookup_Call {
	_c.Call.Return(entityLookup, err)
	return _c
}

func (_c *NetworkRangeClient_EntityLookup_Call) RunAndReturn(run func(context1 context.Context, s string, entityType cato_models.EntityType, n *int64, n1 *int64, entityInput *cato_models.EntityInput, s1 *string, strings []string, sortInputs []*cato_models.SortInput, lookupFilterInputs []*cato_models.LookupFilterInput, strings1 []string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.EntityLookup, error)) *NetworkRangeClient_EntityLookup_Call {
	_c.Call.Return(run)
	return _c
}

// EntityLookupMinimal provides a mock function for the type NetworkRangeClient
func (_mock *NetworkRangeClient) EntityLookupMinimal(context1 context.Context, s string, entityType cato_models.EntityType, n *int64, n1 *int64, entityInput *cato_models.EntityInput, sortInputs []*cato_models.SortInput, lookupFilterInputs []*cato_models.LookupFilterInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.EntityLookup, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, entityType, n, n1, entityInput, sortInputs, lookupFilterInputs, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, entityType, n, n1, entityInput, sortInputs, lookupFilterInputs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EntityLookupMinimal")
	}

	var r0 *cato_go_sdk.EntityLookup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.EntityType, *int64, *int64, *cato_models.EntityInput, []*cato_models.SortInput, []*cato_models.LookupFilterInput, ...clientv2.RequestInterceptor) (*cato_go_sdk.EntityLookup, error)); ok {
		return returnFunc(context1, s, entityType, n, n1, entityInput, sortInputs, lookupFilterInputs, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.EntityType, *int64, *int64, *cato_models.EntityInput, []*cato_models.SortInput, []*cato_models.LookupFilterInput, ...clientv2.RequestInterceptor) *cato_go_sdk.EntityLookup); ok {
		r0 = returnFunc(context1, s, entityType, n, n1, entityInput, sortInputs, lookupFilterInputs, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.EntityLookup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cato_models.EntityType, *int64, *int64, *cato_models.EntityInput, []*cato_models.SortInput, []*cato_models.LookupFilterInput, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, entityType, n, n1, entityInput, sortInputs, lookupFilterInputs, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangeClient_EntityLookupMinimal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EntityLookupMinimal'
type NetworkRangeClient_EntityLookupMinimal_Call struct {
	*mock.Call
}

// EntityLookupMinimal is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - entityType cato_models.EntityType
//   - n *int64
//   - n1 *int64
//   - entityInput *cato_models.EntityInput
//   - sortInputs []*cato_models.SortInput
//   - lookupFilterInputs []*cato_models.LookupFilterInput
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *NetworkRangeClient_Expecter) EntityLookupMinimal(context1 interface{}, s interface{}, entityType interface{}, n interface{}, n1 interface{}, entityInput interface{}, sortInputs interface{}, lookupFilterInputs interface{}, requestInterceptors ...interface{}) *NetworkRangeClient_EntityLookupMinimal_Call {
	return &NetworkRangeClient_EntityLookupMinimal_Call{Call: _e.mock.On("EntityLookupMinimal",
		append([]interface{}{context1, s, entityType, n, n1, entityInput, sortInputs, lookupFilterInputs}, requestInterceptors...)...)}
}

func (_c *NetworkRangeClient_EntityLookupMinimal_Call) Run(run func(context1 context.Context, s string, entityType cato_models.EntityType, n *int64, n1 *int64, entityInput *cato_models.EntityInput, sortInputs []*cato_models.SortInput, lookupFilterInputs []*cato_models.LookupFilterInput, requestInterceptors ...clientv2.RequestInterceptor)) *NetworkRangeClient_EntityLookupMinimal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cato_models.EntityType
		if args[2] != nil {
			arg2 = args[2].(cato_models.EntityType)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 *cato_models.EntityInput
		if args[5] != nil {
			arg5 = args[5].(*cato_models.EntityInput)
		}
		var arg6 []*cato_models.SortInput
		if args[6] != nil {
			arg6 = args[6].([]*cato_models.SortInput)
		}
		var arg7 []*cato_models.LookupFilterInput
		if args[7] != nil {
			arg7 = args[7].([]*cato_models.LookupFilterInput)
		}
		var arg8 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 8 {
			variadicArgs = args[8].([]clientv2.RequestInterceptor)
		}
		arg8 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8...,
		)
	})
	return _c
}

func (_c *NetworkRangeClient_EntityLookupMinimal_Call) Return(entityLookup *cato_go_sdk.EntityLookup, err error) *NetworkRangeClient_EntityLookupMinimal_Call {
	_c.Call.Return(entityLookup, err)
	return _c
}

func (_c *NetworkRangeClient_EntityLookupMinimal_Call) RunAndReturn(run func(context1 context.Context, s string, entityType cato_models.EntityType, n *int64, n1 *int64, entityInput *cato_models.EntityInput, sortInputs []*cato_models.SortInput, lookupFilterInputs []*cato_models.LookupFilterInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.EntityLookup, error)) *NetworkRangeClient_EntityLookupMinimal_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkRange provides a mock function for the type NetworkRangeClient
func (_mock *NetworkRangeClient) NetworkRange(context1 context.Context, s string, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.NetworkRange, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, s1, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for NetworkRange")
	}

	var r0 *cato_go_sdk.NetworkRange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.NetworkRange, error)); ok {
		return returnFunc(context1, s, s1, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv2.RequestInterceptor) *cato_go_sdk.NetworkRange); ok {
		r0 = returnFunc(context1, s, s1, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.NetworkRange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, s1, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangeClient_NetworkRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkRange'
type NetworkRangeClient_NetworkRange_Call struct {
	*mock.Call
}

// NetworkRange is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *NetworkRangeClient_Expecter) NetworkRange(context1 interface{}, s interface{}, s1 interface{}, requestInterceptors ...interface{}) *NetworkRangeClient_NetworkRange_Call {
	return &NetworkRangeClient_NetworkRange_Call{Call: _e.mock.On("NetworkRange",
		append([]interface{}{context1, s, s1}, requestInterceptors...)...)}
}

func (_c *NetworkRangeClient_NetworkRange_Call) Run(run func(context1 context.Context, s string, s1 string, requestInterceptors ...clientv2.RequestInterceptor)) *NetworkRangeClient_NetworkRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *NetworkRangeClient_NetworkRange_Call) Return(networkRange *cato_go_sdk.NetworkRange, err error) *NetworkRangeClient_NetworkRange_Call {
	_c.Call.Return(networkRange, err)
	return _c
}

func (_c *NetworkRangeClient_NetworkRange_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.NetworkRange, error)) *NetworkRangeClient_NetworkRange_Call {
	_c.Call.Return(run)
	return _c
}

// SiteAddNetworkRange provides a mock function for the type NetworkRangeClient
func (_mock *NetworkRangeClient) SiteAddNetworkRange(context1 context.Context, s string, addNetworkRangeInput cato_models.AddNetworkRangeInput, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteAddNetworkRange, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, addNetworkRangeInput, s1, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, addNetworkRangeInput, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SiteAddNetworkRange")
	}

	var r0 *cato_go_sdk.SiteAddNetworkRange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.AddNetworkRangeInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteAddNetworkRange, error)); ok {
		return returnFunc(context1, s, addNetworkRangeInput, s1, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.AddNetworkRangeInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.SiteAddNetworkRange); ok {
		r0 = returnFunc(context1, s, addNetworkRangeInput, s1, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.SiteAddNetworkRange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cato_models.AddNetworkRangeInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, addNetworkRangeInput, s1, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangeClient_SiteAddNetworkRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SiteAddNetworkRange'
type NetworkRangeClient_SiteAddNetworkRange_Call struct {
	*mock.Call
}

// SiteAddNetworkRange is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - addNetworkRangeInput cato_models.AddNetworkRangeInput
//   - s1 string
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *NetworkRangeClient_Expecter) SiteAddNetworkRange(context1 interface{}, s interface{}, addNetworkRangeInput interface{}, s1 interface{}, requestInterceptors ...interface{}) *NetworkRangeClient_SiteAddNetworkRange_Call {
	return &NetworkRangeClient_SiteAddNetworkRange_Call{Call: _e.mock.On("SiteAddNetworkRange",
		append([]interface{}{context1, s, addNetworkRangeInput, s1}, requestInterceptors...)...)}
}

func (_c *NetworkRangeClient_SiteAddNetworkRange_Call) Run(run func(context1 context.Context, s string, addNetworkRangeInput cato_models.AddNetworkRangeInput, s1 string, requestInterceptors ...clientv2.RequestInterceptor)) *NetworkRangeClient_SiteAddNetworkRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cato_models.AddNetworkRangeInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.AddNetworkRangeInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *NetworkRangeClient_SiteAddNetworkRange_Call) Return(siteAddNetworkRange *cato_go_sdk.SiteAddNetworkRange, err error) *NetworkRangeClient_SiteAddNetworkRange_Call {
	_c.Call.Return(siteAddNetworkRange, err)
	return _c
}

func (_c *NetworkRangeClient_SiteAddNetworkRange_Call) RunAndReturn(run func(context1 context.Context, s string, addNetworkRangeInput cato_models.AddNetworkRangeInput, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteAddNetworkRange, error)) *NetworkRangeClient_SiteAddNetworkRange_Call {
	_c.Call.Return(run)
	return _c
}

// SiteRemoveNetworkRange provides a mock function for the type NetworkRangeClient
func (_mock *NetworkRangeClient) SiteRemoveNetworkRange(context1 context.Context, s string, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteRemoveNetworkRange, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, s1, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SiteRemoveNetworkRange")
	}

	var r0 *cato_go_sdk.SiteRemoveNetworkRange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteRemoveNetworkRange, error)); ok {
		return returnFunc(context1, s, s1, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv2.RequestInterceptor) *cato_go_sdk.SiteRemoveNetworkRange); ok {
		r0 = returnFunc(context1, s, s1, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.SiteRemoveNetworkRange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, s1, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangeClient_SiteRemoveNetworkRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SiteRemoveNetworkRange'
type NetworkRangeClient_SiteRemoveNetworkRange_Call struct {
	*mock.Call
}

// SiteRemoveNetworkRange is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *NetworkRangeClient_Expecter) SiteRemoveNetworkRange(context1 interface{}, s interface{}, s1 interface{}, requestInterceptors ...interface{}) *NetworkRangeClient_SiteRemoveNetworkRange_Call {
	return &NetworkRangeClient_SiteRemoveNetworkRange_Call{Call: _e.mock.On("SiteRemoveNetworkRange",
		append([]interface{}{context1, s, s1}, requestInterceptors...)...)}
}

func (_c *NetworkRangeClient_SiteRemoveNetworkRange_Call) Run(run func(context1 context.Context, s string, s1 string, requestInterceptors ...clientv2.RequestInterceptor)) *NetworkRangeClient_SiteRemoveNetworkRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *NetworkRangeClient_SiteRemoveNetworkRange_Call) Return(siteRemoveNetworkRange *cato_go_sdk.SiteRemoveNetworkRange, err error) *NetworkRangeClient_SiteRemoveNetworkRange_Call {
	_c.Call.Return(siteRemoveNetworkRange, err)
	return _c
}

func (_c *NetworkRangeClient_SiteRemoveNetworkRange_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteRemoveNetworkRange, error)) *NetworkRangeClient_SiteRemoveNetworkRange_Call {
	_c.Call.Return(run)
	return _c
}

// SiteUpdateNetworkRange provides a mock function for the type NetworkRangeClient
func (_mock *NetworkRangeClient) SiteUpdateNetworkRange(context1 context.Context, s string, updateNetworkRangeInput cato_models.UpdateNetworkRangeInput, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteUpdateNetworkRange, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, updateNetworkRangeInput, s1, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, updateNetworkRangeInput, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SiteUpdateNetworkRange")
	}

	var r0 *cato_go_sdk.SiteUpdateNetworkRange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.UpdateNetworkRangeInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteUpdateNetworkRange, error)); ok {
		return returnFunc(context1, s, updateNetworkRangeInput, s1, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.UpdateNetworkRangeInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.SiteUpdateNetworkRange); ok {
		r0 = returnFunc(context1, s, updateNetworkRangeInput, s1, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.SiteUpdateNetworkRange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cato_models.UpdateNetworkRangeInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, updateNetworkRangeInput, s1, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkRangeClient_SiteUpdateNetworkRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SiteUpdateNetworkRange'
type NetworkRangeClient_SiteUpdateNetworkRange_Call struct {
	*mock.Call
}

// SiteUpdateNetworkRange is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - updateNetworkRangeInput cato_models.UpdateNetworkRangeInput
//   - s1 string
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *NetworkRangeClient_Expecter) SiteUpdateNetworkRange(context1 interface{}, s interface{}, updateNetworkRangeInput interface{}, s1 interface{}, requestInterceptors ...interface{}) *NetworkRangeClient_SiteUpdateNetworkRange_Call {
	return &NetworkRangeClient_SiteUpdateNetworkRange_Call{Call: _e.mock.On("SiteUpdateNetworkRange",
		append([]interface{}{context1, s, updateNetworkRangeInput, s1}, requestInterceptors...)...)}
}

func (_c *NetworkRangeClient_SiteUpdateNetworkRange_Call) Run(run func(context1 context.Context, s string, updateNetworkRangeInput cato_models.UpdateNetworkRangeInput, s1 string, requestInterceptors ...clientv2.RequestInterceptor)) *NetworkRangeClient_SiteUpdateNetworkRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cato_models.UpdateNetworkRangeInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.UpdateNetworkRangeInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *NetworkRangeClient_SiteUpdateNetworkRange_Call) Return(siteUpdateNetworkRange *cato_go_sdk.SiteUpdateNetworkRange, err error) *NetworkRangeClient_SiteUpdateNetworkRange_Call {
	_c.Call.Return(siteUpdateNetworkRange, err)
	return _c
}

func (_c *NetworkRangeClient_SiteUpdateNetworkRange_Call) RunAndReturn(run func(context1 context.Context, s string, updateNetworkRangeInput cato_models.UpdateNetworkRangeInput, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteUpdateNetworkRange, error)) *NetworkRangeClient_SiteUpdateNetworkRange_Call {
	_c.Call.Return(run)
	return _c
}
