// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Yamashou/gqlgenc/clientv2"
	cato_go_sdk "github.com/catonetworks/cato-go-sdk"
	cato_models "github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewRoleManagementClient creates a new instance of RoleManagementClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleManagementClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleManagementClient {
	mock := &RoleManagementClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleManagementClient is an autogenerated mock type for the RoleManagementClient type
type RoleManagementClient struct {
	mock.Mock
}

type RoleManagementClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleManagementClient) EXPECT() *RoleManagementClient_Expecter {
	return &RoleManagementClient_Expecter{mock: &_m.Mock}
}

// RbacRoleManagementCreateRole provides a mock function for the type RoleManagementClient
func (_mock *RoleManagementClient) RbacRoleManagementCreateRole(context1 context.Context, s string, roleManagementCreateRoleInput cato_models.RoleManagementCreateRoleInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementCreateRole, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, roleManagementCreateRoleInput, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, roleManagementCreateRoleInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RbacRoleManagementCreateRole")
	}

	var r0 *cato_go_sdk.RbacRoleManagementCreateRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.RoleManagementCreateRoleInput, ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementCreateRole, error)); ok {
		return returnFunc(context1, s, roleManagementCreateRoleInput, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.RoleManagementCreateRoleInput, ...clientv2.RequestInterceptor) *cato_go_sdk.RbacRoleManagementCreateRole); ok {
		r0 = returnFunc(context1, s, roleManagementCreateRoleInput, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.RbacRoleManagementCreateRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cato_models.RoleManagementCreateRoleInput, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, roleManagementCreateRoleInput, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleManagementClient_RbacRoleManagementCreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacRoleManagementCreateRole'
type RoleManagementClient_RbacRoleManagementCreateRole_Call struct {
	*mock.Call
}

// RbacRoleManagementCreateRole is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - roleManagementCreateRoleInput cato_models.RoleManagementCreateRoleInput
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *RoleManagementClient_Expecter) RbacRoleManagementCreateRole(context1 interface{}, s interface{}, roleManagementCreateRoleInput interface{}, requestInterceptors ...interface{}) *RoleManagementClient_RbacRoleManagementCreateRole_Call {
	return &RoleManagementClient_RbacRoleManagementCreateRole_Call{Call: _e.mock.On("RbacRoleManagementCreateRole",
		append([]interface{}{context1, s, roleManagementCreateRoleInput}, requestInterceptors...)...)}
}

func (_c *RoleManagementClient_RbacRoleManagementCreateRole_Call) Run(run func(context1 context.Context, s string, roleManagementCreateRoleInput cato_models.RoleManagementCreateRoleInput, requestInterceptors ...clientv2.RequestInterceptor)) *RoleManagementClient_RbacRoleManagementCreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cato_models.RoleManagementCreateRoleInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.RoleManagementCreateRoleInput)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementCreateRole_Call) Return(rbacRoleManagementCreateRole *cato_go_sdk.RbacRoleManagementCreateRole, err error) *RoleManagementClient_RbacRoleManagementCreateRole_Call {
	_c.Call.Return(rbacRoleManagementCreateRole, err)
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementCreateRole_Call) RunAndReturn(run func(context1 context.Context, s string, roleManagementCreateRoleInput cato_models.RoleManagementCreateRoleInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementCreateRole, error)) *RoleManagementClient_RbacRoleManagementCreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// RbacRoleManagementDeleteRole provides a mock function for the type RoleManagementClient
func (_mock *RoleManagementClient) RbacRoleManagementDeleteRole(context1 context.Context, s string, roleManagementDeleteRoleInput cato_models.RoleManagementDeleteRoleInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementDeleteRole, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, roleManagementDeleteRoleInput, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, roleManagementDeleteRoleInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RbacRoleManagementDeleteRole")
	}

	var r0 *cato_go_sdk.RbacRoleManagementDeleteRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.RoleManagementDeleteRoleInput, ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementDeleteRole, error)); ok {
		return returnFunc(context1, s, roleManagementDeleteRoleInput, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.RoleManagementDeleteRoleInput, ...clientv2.RequestInterceptor) *cato_go_sdk.RbacRoleManagementDeleteRole); ok {
		r0 = returnFunc(context1, s, roleManagementDeleteRoleInput, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.RbacRoleManagementDeleteRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cato_models.RoleManagementDeleteRoleInput, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, roleManagementDeleteRoleInput, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleManagementClient_RbacRoleManagementDeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacRoleManagementDeleteRole'
type RoleManagementClient_RbacRoleManagementDeleteRole_Call struct {
	*mock.Call
}

// RbacRoleManagementDeleteRole is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - roleManagementDeleteRoleInput cato_models.RoleManagementDeleteRoleInput
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *RoleManagementClient_Expecter) RbacRoleManagementDeleteRole(context1 interface{}, s interface{}, roleManagementDeleteRoleInput interface{}, requestInterceptors ...interface{}) *RoleManagementClient_RbacRoleManagementDeleteRole_Call {
	return &RoleManagementClient_RbacRoleManagementDeleteRole_Call{Call: _e.mock.On("RbacRoleManagementDeleteRole",
		append([]interface{}{context1, s, roleManagementDeleteRoleInput}, requestInterceptors...)...)}
}

func (_c *RoleManagementClient_RbacRoleManagementDeleteRole_Call) Run(run func(context1 context.Context, s string, roleManagementDeleteRoleInput cato_models.RoleManagementDeleteRoleInput, requestInterceptors ...clientv2.RequestInterceptor)) *RoleManagementClient_RbacRoleManagementDeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cato_models.RoleManagementDeleteRoleInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.RoleManagementDeleteRoleInput)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementDeleteRole_Call) Return(rbacRoleManagementDeleteRole *cato_go_sdk.RbacRoleManagementDeleteRole, err error) *RoleManagementClient_RbacRoleManagementDeleteRole_Call {
	_c.Call.Return(rbacRoleManagementDeleteRole, err)
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementDeleteRole_Call) RunAndReturn(run func(context1 context.Context, s string, roleManagementDeleteRoleInput cato_models.RoleManagementDeleteRoleInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementDeleteRole, error)) *RoleManagementClient_RbacRoleManagementDeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// RbacRoleManagementPermissionCatalog provides a mock function for the type RoleManagementClient
func (_mock *RoleManagementClient) RbacRoleManagementPermissionCatalog(context1 context.Context, s string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementPermissionCatalog, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RbacRoleManagementPermissionCatalog")
	}

	var r0 *cato_go_sdk.RbacRoleManagementPermissionCatalog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementPermissionCatalog, error)); ok {
		return returnFunc(context1, s, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) *cato_go_sdk.RbacRoleManagementPermissionCatalog); ok {
		r0 = returnFunc(context1, s, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.RbacRoleManagementPermissionCatalog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleManagementClient_RbacRoleManagementPermissionCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacRoleManagementPermissionCatalog'
type RoleManagementClient_RbacRoleManagementPermissionCatalog_Call struct {
	*mock.Call
}

// RbacRoleManagementPermissionCatalog is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *RoleManagementClient_Expecter) RbacRoleManagementPermissionCatalog(context1 interface{}, s interface{}, requestInterceptors ...interface{}) *RoleManagementClient_RbacRoleManagementPermissionCatalog_Call {
	return &RoleManagementClient_RbacRoleManagementPermissionCatalog_Call{Call: _e.mock.On("RbacRoleManagementPermissionCatalog",
		append([]interface{}{context1, s}, requestInterceptors...)...)}
}

func (_c *RoleManagementClient_RbacRoleManagementPermissionCatalog_Call) Run(run func(context1 context.Context, s string, requestInterceptors ...clientv2.RequestInterceptor)) *RoleManagementClient_RbacRoleManagementPermissionCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv2.RequestInterceptor)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementPermissionCatalog_Call) Return(rbacRoleManagementPermissionCatalog *cato_go_sdk.RbacRoleManagementPermissionCatalog, err error) *RoleManagementClient_RbacRoleManagementPermissionCatalog_Call {
	_c.Call.Return(rbacRoleManagementPermissionCatalog, err)
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementPermissionCatalog_Call) RunAndReturn(run func(context1 context.Context, s string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementPermissionCatalog, error)) *RoleManagementClient_RbacRoleManagementPermissionCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// RbacRoleManagementRole provides a mock function for the type RoleManagementClient
func (_mock *RoleManagementClient) RbacRoleManagementRole(context1 context.Context, s string, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementRole, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, s1, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RbacRoleManagementRole")
	}

	var r0 *cato_go_sdk.RbacRoleManagementRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementRole, error)); ok {
		return returnFunc(context1, s, s1, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv2.RequestInterceptor) *cato_go_sdk.RbacRoleManagementRole); ok {
		r0 = returnFunc(context1, s, s1, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.RbacRoleManagementRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, s1, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleManagementClient_RbacRoleManagementRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacRoleManagementRole'
type RoleManagementClient_RbacRoleManagementRole_Call struct {
	*mock.Call
}

// RbacRoleManagementRole is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *RoleManagementClient_Expecter) RbacRoleManagementRole(context1 interface{}, s interface{}, s1 interface{}, requestInterceptors ...interface{}) *RoleManagementClient_RbacRoleManagementRole_Call {
	return &RoleManagementClient_RbacRoleManagementRole_Call{Call: _e.mock.On("RbacRoleManagementRole",
		append([]interface{}{context1, s, s1}, requestInterceptors...)...)}
}

func (_c *RoleManagementClient_RbacRoleManagementRole_Call) Run(run func(context1 context.Context, s string, s1 string, requestInterceptors ...clientv2.RequestInterceptor)) *RoleManagementClient_RbacRoleManagementRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementRole_Call) Return(rbacRoleManagementRole *cato_go_sdk.RbacRoleManagementRole, err error) *RoleManagementClient_RbacRoleManagementRole_Call {
	_c.Call.Return(rbacRoleManagementRole, err)
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementRole_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementRole, error)) *RoleManagementClient_RbacRoleManagementRole_Call {
	_c.Call.Return(run)
	return _c
}

// RbacRoleManagementRoleList provides a mock function for the type RoleManagementClient
func (_mock *RoleManagementClient) RbacRoleManagementRoleList(context1 context.Context, s string, roleManagementRoleListInput cato_models.RoleManagementRoleListInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementRoleList, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, roleManagementRoleListInput, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, roleManagementRoleListInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RbacRoleManagementRoleList")
	}

	var r0 *cato_go_sdk.RbacRoleManagementRoleList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.RoleManagementRoleListInput, ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementRoleList, error)); ok {
		return returnFunc(context1, s, roleManagementRoleListInput, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.RoleManagementRoleListInput, ...clientv2.RequestInterceptor) *cato_go_sdk.RbacRoleManagementRoleList); ok {
		r0 = returnFunc(context1, s, roleManagementRoleListInput, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.RbacRoleManagementRoleList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cato_models.RoleManagementRoleListInput, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, roleManagementRoleListInput, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleManagementClient_RbacRoleManagementRoleList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacRoleManagementRoleList'
type RoleManagementClient_RbacRoleManagementRoleList_Call struct {
	*mock.Call
}

// RbacRoleManagementRoleList is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - roleManagementRoleListInput cato_models.RoleManagementRoleListInput
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *RoleManagementClient_Expecter) RbacRoleManagementRoleList(context1 interface{}, s interface{}, roleManagementRoleListInput interface{}, requestInterceptors ...interface{}) *RoleManagementClient_RbacRoleManagementRoleList_Call {
	return &RoleManagementClient_RbacRoleManagementRoleList_Call{Call: _e.mock.On("RbacRoleManagementRoleList",
		append([]interface{}{context1, s, roleManagementRoleListInput}, requestInterceptors...)...)}
}

func (_c *RoleManagementClient_RbacRoleManagementRoleList_Call) Run(run func(context1 context.Context, s string, roleManagementRoleListInput cato_models.RoleManagementRoleListInput, requestInterceptors ...clientv2.RequestInterceptor)) *RoleManagementClient_RbacRoleManagementRoleList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cato_models.RoleManagementRoleListInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.RoleManagementRoleListInput)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementRoleList_Call) Return(rbacRoleManagementRoleList *cato_go_sdk.RbacRoleManagementRoleList, err error) *RoleManagementClient_RbacRoleManagementRoleList_Call {
	_c.Call.Return(rbacRoleManagementRoleList, err)
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementRoleList_Call) RunAndReturn(run func(context1 context.Context, s string, roleManagementRoleListInput cato_models.RoleManagementRoleListInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementRoleList, error)) *RoleManagementClient_RbacRoleManagementRoleList_Call {
	_c.Call.Return(run)
	return _c
}

// RbacRoleManagementUpdateRole provides a mock function for the type RoleManagementClient
func (_mock *RoleManagementClient) RbacRoleManagementUpdateRole(context1 context.Context, s string, roleManagementUpdateRoleInput cato_models.RoleManagementUpdateRoleInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementUpdateRole, error) {
	var tmpRet mock.Arguments
	if len(requestInterceptors) > 0 {
		tmpRet = _mock.Called(context1, s, roleManagementUpdateRoleInput, requestInterceptors)
	} else {
		tmpRet = _mock.Called(context1, s, roleManagementUpdateRoleInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RbacRoleManagementUpdateRole")
	}

	var r0 *cato_go_sdk.RbacRoleManagementUpdateRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.RoleManagementUpdateRoleInput, ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementUpdateRole, error)); ok {
		return returnFunc(context1, s, roleManagementUpdateRoleInput, requestInterceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.RoleManagementUpdateRoleInput, ...clientv2.RequestInterceptor) *cato_go_sdk.RbacRoleManagementUpdateRole); ok {
		r0 = returnFunc(context1, s, roleManagementUpdateRoleInput, requestInterceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.RbacRoleManagementUpdateRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cato_models.RoleManagementUpdateRoleInput, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(context1, s, roleManagementUpdateRoleInput, requestInterceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleManagementClient_RbacRoleManagementUpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacRoleManagementUpdateRole'
type RoleManagementClient_RbacRoleManagementUpdateRole_Call struct {
	*mock.Call
}

// RbacRoleManagementUpdateRole is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - roleManagementUpdateRoleInput cato_models.RoleManagementUpdateRoleInput
//   - requestInterceptors ...clientv2.RequestInterceptor
func (_e *RoleManagementClient_Expecter) RbacRoleManagementUpdateRole(context1 interface{}, s interface{}, roleManagementUpdateRoleInput interface{}, requestInterceptors ...interface{}) *RoleManagementClient_RbacRoleManagementUpdateRole_Call {
	return &RoleManagementClient_RbacRoleManagementUpdateRole_Call{Call: _e.mock.On("RbacRoleManagementUpdateRole",
		append([]interface{}{context1, s, roleManagementUpdateRoleInput}, requestInterceptors...)...)}
}

func (_c *RoleManagementClient_RbacRoleManagementUpdateRole_Call) Run(run func(context1 context.Context, s string, roleManagementUpdateRoleInput cato_models.RoleManagementUpdateRoleInput, requestInterceptors ...clientv2.RequestInterceptor)) *RoleManagementClient_RbacRoleManagementUpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cato_models.RoleManagementUpdateRoleInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.RoleManagementUpdateRoleInput)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementUpdateRole_Call) Return(rbacRoleManagementUpdateRole *cato_go_sdk.RbacRoleManagementUpdateRole, err error) *RoleManagementClient_RbacRoleManagementUpdateRole_Call {
	_c.Call.Return(rbacRoleManagementUpdateRole, err)
	return _c
}

func (_c *RoleManagementClient_RbacRoleManagementUpdateRole_Call) RunAndReturn(run func(context1 context.Context, s string, roleManagementUpdateRoleInput cato_models.RoleManagementUpdateRoleInput, requestInterceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.RbacRoleManagementUpdateRole, error)) *RoleManagementClient_RbacRoleManagementUpdateRole_Call {
	_c.Call.Return(run)
	return _c
}
