// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/catonetworks/terraform-provider-cato/internal/provider/network/sktsite/application"
)

// NewSocketSitePort creates a new instance of SocketSitePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSocketSitePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *SocketSitePort {
	mock := &SocketSitePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SocketSitePort is an autogenerated mock type for the SocketSitePort type
type SocketSitePort struct {
	mock.Mock
}

type SocketSitePort_Expecter struct {
	mock *mock.Mock
}

func (_m *SocketSitePort) EXPECT() *SocketSitePort_Expecter {
	return &SocketSitePort_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) Add(context1 context.Context, addInput application.AddInput) (string, error) {
	ret := _mock.Called(context1, addInput)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.AddInput) (string, error)); ok {
		return returnFunc(context1, addInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.AddInput) string); ok {
		r0 = returnFunc(context1, addInput)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.AddInput) error); ok {
		r1 = returnFunc(context1, addInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SocketSitePort_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type SocketSitePort_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - context1 context.Context
//   - addInput application.AddInput
func (_e *SocketSitePort_Expecter) Add(context1 interface{}, addInput interface{}) *SocketSitePort_Add_Call {
	return &SocketSitePort_Add_Call{Call: _e.mock.On("Add", context1, addInput)}
}

func (_c *SocketSitePort_Add_Call) Run(run func(context1 context.Context, addInput application.AddInput)) *SocketSitePort_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.AddInput
		if args[1] != nil {
			arg1 = args[1].(application.AddInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SocketSitePort_Add_Call) Return(s string, err error) *SocketSitePort_Add_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *SocketSitePort_Add_Call) RunAndReturn(run func(context1 context.Context, addInput application.AddInput) (string, error)) *SocketSitePort_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Configuration provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) Configuration(context1 context.Context, s string) (*application.Configuration, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Configuration")
	}

	var r0 *application.Configuration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*application.Configuration, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *application.Configuration); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.Configuration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SocketSitePort_Configuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configuration'
type SocketSitePort_Configuration_Call struct {
	*mock.Call
}

// Configuration is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *SocketSitePort_Expecter) Configuration(context1 interface{}, s interface{}) *SocketSitePort_Configuration_Call {
	return &SocketSitePort_Configuration_Call{Call: _e.mock.On("Configuration", context1, s)}
}

func (_c *SocketSitePort_Configuration_Call) Run(run func(context1 context.Context, s string)) *SocketSitePort_Configuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SocketSitePort_Configuration_Call) Return(configuration *application.Configuration, err error) *SocketSitePort_Configuration_Call {
	_c.Call.Return(configuration, err)
	return _c
}

func (_c *SocketSitePort_Configuration_Call) RunAndReturn(run func(context1 context.Context, s string) (*application.Configuration, error)) *SocketSitePort_Configuration_Call {
	_c.Call.Return(run)
	return _c
}

// DefaultInterface provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) DefaultInterface(context1 context.Context, s string, s1 string) (*application.Interface, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for DefaultInterface")
	}

	var r0 *application.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*application.Interface, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *application.Interface); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SocketSitePort_DefaultInterface_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultInterface'
type SocketSitePort_DefaultInterface_Call struct {
	*mock.Call
}

// DefaultInterface is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *SocketSitePort_Expecter) DefaultInterface(context1 interface{}, s interface{}, s1 interface{}) *SocketSitePort_DefaultInterface_Call {
	return &SocketSitePort_DefaultInterface_Call{Call: _e.mock.On("DefaultInterface", context1, s, s1)}
}

func (_c *SocketSitePort_DefaultInterface_Call) Run(run func(context1 context.Context, s string, s1 string)) *SocketSitePort_DefaultInterface_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SocketSitePort_DefaultInterface_Call) Return(interfaceParam *application.Interface, err error) *SocketSitePort_DefaultInterface_Call {
	_c.Call.Return(interfaceParam, err)
	return _c
}

func (_c *SocketSitePort_DefaultInterface_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (*application.Interface, error)) *SocketSitePort_DefaultInterface_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) Exchange(context1 context.Context, s string, s1 string, s2 string) error {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SocketSitePort_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type SocketSitePort_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *SocketSitePort_Expecter) Exchange(context1 interface{}, s interface{}, s1 interface{}, s2 interface{}) *SocketSitePort_Exchange_Call {
	return &SocketSitePort_Exchange_Call{Call: _e.mock.On("Exchange", context1, s, s1, s2)}
}

func (_c *SocketSitePort_Exchange_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *SocketSitePort_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SocketSitePort_Exchange_Call) Return(err error) *SocketSitePort_Exchange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SocketSitePort_Exchange_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) error) *SocketSitePort_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) Exists(context1 context.Context, s string) (bool, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SocketSitePort_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type SocketSitePort_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *SocketSitePort_Expecter) Exists(context1 interface{}, s interface{}) *SocketSitePort_Exists_Call {
	return &SocketSitePort_Exists_Call{Call: _e.mock.On("Exists", context1, s)}
}

func (_c *SocketSitePort_Exists_Call) Run(run func(context1 context.Context, s string)) *SocketSitePort_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SocketSitePort_Exists_Call) Return(b bool, err error) *SocketSitePort_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *SocketSitePort_Exists_Call) RunAndReturn(run func(context1 context.Context, s string) (bool, error)) *SocketSitePort_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// General provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) General(context1 context.Context, s string) (*application.Snapshot, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for General")
	}

	var r0 *application.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*application.Snapshot, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *application.Snapshot); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SocketSitePort_General_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'General'
type SocketSitePort_General_Call struct {
	*mock.Call
}

// General is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *SocketSitePort_Expecter) General(context1 interface{}, s interface{}) *SocketSitePort_General_Call {
	return &SocketSitePort_General_Call{Call: _e.mock.On("General", context1, s)}
}

func (_c *SocketSitePort_General_Call) Run(run func(context1 context.Context, s string)) *SocketSitePort_General_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SocketSitePort_General_Call) Return(snapshot *application.Snapshot, err error) *SocketSitePort_General_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *SocketSitePort_General_Call) RunAndReturn(run func(context1 context.Context, s string) (*application.Snapshot, error)) *SocketSitePort_General_Call {
	_c.Call.Return(run)
	return _c
}

// NativeRange provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) NativeRange(context1 context.Context, s string) (*application.Range, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for NativeRange")
	}

	var r0 *application.Range
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*application.Range, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *application.Range); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.Range)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SocketSitePort_NativeRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NativeRange'
type SocketSitePort_NativeRange_Call struct {
	*mock.Call
}

// NativeRange is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *SocketSitePort_Expecter) NativeRange(context1 interface{}, s interface{}) *SocketSitePort_NativeRange_Call {
	return &SocketSitePort_NativeRange_Call{Call: _e.mock.On("NativeRange", context1, s)}
}

func (_c *SocketSitePort_NativeRange_Call) Run(run func(context1 context.Context, s string)) *SocketSitePort_NativeRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SocketSitePort_NativeRange_Call) Return(rangeParam *application.Range, err error) *SocketSitePort_NativeRange_Call {
	_c.Call.Return(rangeParam, err)
	return _c
}

func (_c *SocketSitePort_NativeRange_Call) RunAndReturn(run func(context1 context.Context, s string) (*application.Range, error)) *SocketSitePort_NativeRange_Call {
	_c.Call.Return(run)
	return _c
}

// RelayID provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) RelayID(context1 context.Context, s string) (string, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RelayID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SocketSitePort_RelayID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RelayID'
type SocketSitePort_RelayID_Call struct {
	*mock.Call
}

// RelayID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *SocketSitePort_Expecter) RelayID(context1 interface{}, s interface{}) *SocketSitePort_RelayID_Call {
	return &SocketSitePort_RelayID_Call{Call: _e.mock.On("RelayID", context1, s)}
}

func (_c *SocketSitePort_RelayID_Call) Run(run func(context1 context.Context, s string)) *SocketSitePort_RelayID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SocketSitePort_RelayID_Call) Return(s1 string, err error) *SocketSitePort_RelayID_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *SocketSitePort_RelayID_Call) RunAndReturn(run func(context1 context.Context, s string) (string, error)) *SocketSitePort_RelayID_Call {
	_c.Call.Return(run)
	return _c
}

// RelayName provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) RelayName(context1 context.Context, s string) (*string, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RelayName")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SocketSitePort_RelayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RelayName'
type SocketSitePort_RelayName_Call struct {
	*mock.Call
}

// RelayName is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *SocketSitePort_Expecter) RelayName(context1 interface{}, s interface{}) *SocketSitePort_RelayName_Call {
	return &SocketSitePort_RelayName_Call{Call: _e.mock.On("RelayName", context1, s)}
}

func (_c *SocketSitePort_RelayName_Call) Run(run func(context1 context.Context, s string)) *SocketSitePort_RelayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SocketSitePort_RelayName_Call) Return(s1 *string, err error) *SocketSitePort_RelayName_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *SocketSitePort_RelayName_Call) RunAndReturn(run func(context1 context.Context, s string) (*string, error)) *SocketSitePort_RelayName_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) Remove(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SocketSitePort_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type SocketSitePort_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *SocketSitePort_Expecter) Remove(context1 interface{}, s interface{}) *SocketSitePort_Remove_Call {
	return &SocketSitePort_Remove_Call{Call: _e.mock.On("Remove", context1, s)}
}

func (_c *SocketSitePort_Remove_Call) Run(run func(context1 context.Context, s string)) *SocketSitePort_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SocketSitePort_Remove_Call) Return(err error) *SocketSitePort_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SocketSitePort_Remove_Call) RunAndReturn(run func(context1 context.Context, s string) error) *SocketSitePort_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGeneral provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) UpdateGeneral(context1 context.Context, s string, generalInput application.GeneralInput) error {
	ret := _mock.Called(context1, s, generalInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGeneral")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, application.GeneralInput) error); ok {
		r0 = returnFunc(context1, s, generalInput)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SocketSitePort_UpdateGeneral_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGeneral'
type SocketSitePort_UpdateGeneral_Call struct {
	*mock.Call
}

// UpdateGeneral is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - generalInput application.GeneralInput
func (_e *SocketSitePort_Expecter) UpdateGeneral(context1 interface{}, s interface{}, generalInput interface{}) *SocketSitePort_UpdateGeneral_Call {
	return &SocketSitePort_UpdateGeneral_Call{Call: _e.mock.On("UpdateGeneral", context1, s, generalInput)}
}

func (_c *SocketSitePort_UpdateGeneral_Call) Run(run func(context1 context.Context, s string, generalInput application.GeneralInput)) *SocketSitePort_UpdateGeneral_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 application.GeneralInput
		if args[2] != nil {
			arg2 = args[2].(application.GeneralInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SocketSitePort_UpdateGeneral_Call) Return(err error) *SocketSitePort_UpdateGeneral_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SocketSitePort_UpdateGeneral_Call) RunAndReturn(run func(context1 context.Context, s string, generalInput application.GeneralInput) error) *SocketSitePort_UpdateGeneral_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInterface provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) UpdateInterface(context1 context.Context, s string, s1 string, interfaceInput application.InterfaceInput) error {
	ret := _mock.Called(context1, s, s1, interfaceInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInterface")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, application.InterfaceInput) error); ok {
		r0 = returnFunc(context1, s, s1, interfaceInput)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SocketSitePort_UpdateInterface_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInterface'
type SocketSitePort_UpdateInterface_Call struct {
	*mock.Call
}

// UpdateInterface is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - interfaceInput application.InterfaceInput
func (_e *SocketSitePort_Expecter) UpdateInterface(context1 interface{}, s interface{}, s1 interface{}, interfaceInput interface{}) *SocketSitePort_UpdateInterface_Call {
	return &SocketSitePort_UpdateInterface_Call{Call: _e.mock.On("UpdateInterface", context1, s, s1, interfaceInput)}
}

func (_c *SocketSitePort_UpdateInterface_Call) Run(run func(context1 context.Context, s string, s1 string, interfaceInput application.InterfaceInput)) *SocketSitePort_UpdateInterface_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 application.InterfaceInput
		if args[3] != nil {
			arg3 = args[3].(application.InterfaceInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SocketSitePort_UpdateInterface_Call) Return(err error) *SocketSitePort_UpdateInterface_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SocketSitePort_UpdateInterface_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, interfaceInput application.InterfaceInput) error) *SocketSitePort_UpdateInterface_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRange provides a mock function for the type SocketSitePort
func (_mock *SocketSitePort) UpdateRange(context1 context.Context, s string, rangeInput application.RangeInput) error {
	ret := _mock.Called(context1, s, rangeInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, application.RangeInput) error); ok {
		r0 = returnFunc(context1, s, rangeInput)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SocketSitePort_UpdateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRange'
type SocketSitePort_UpdateRange_Call struct {
	*mock.Call
}

// UpdateRange is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - rangeInput application.RangeInput
func (_e *SocketSitePort_Expecter) UpdateRange(context1 interface{}, s interface{}, rangeInput interface{}) *SocketSitePort_UpdateRange_Call {
	return &SocketSitePort_UpdateRange_Call{Call: _e.mock.On("UpdateRange", context1, s, rangeInput)}
}

func (_c *SocketSitePort_UpdateRange_Call) Run(run func(context1 context.Context, s string, rangeInput application.RangeInput)) *SocketSitePort_UpdateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 application.RangeInput
		if args[2] != nil {
			arg2 = args[2].(application.RangeInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SocketSitePort_UpdateRange_Call) Return(err error) *SocketSitePort_UpdateRange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SocketSitePort_UpdateRange_Call) RunAndReturn(run func(context1 context.Context, s string, rangeInput application.RangeInput) error) *SocketSitePort_UpdateRange_Call {
	_c.Call.Return(run)
	return _c
}
