// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Yamashou/gqlgenc/clientv2"
	cato_go_sdk "github.com/catonetworks/cato-go-sdk"
	cato_models "github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewSocketSiteClient creates a new instance of SocketSiteClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSocketSiteClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SocketSiteClient {
	mock := &SocketSiteClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SocketSiteClient is an autogenerated mock type for the SocketSiteClient type
type SocketSiteClient struct {
	mock.Mock
}

type SocketSiteClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SocketSiteClient) EXPECT() *SocketSiteClient_Expecter {
	return &SocketSiteClient_Expecter{mock: &_m.Mock}
}

// SiteAddSocketSite provides a mock function for the type SocketSiteClient
func (_mock *SocketSiteClient) SiteAddSocketSite(ctx context.Context, addSocketSiteInput cato_models.AddSocketSiteInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteAddSocketSite, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, addSocketSiteInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, addSocketSiteInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SiteAddSocketSite")
	}

	var r0 *cato_go_sdk.SiteAddSocketSite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.AddSocketSiteInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteAddSocketSite, error)); ok {
		return returnFunc(ctx, addSocketSiteInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.AddSocketSiteInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.SiteAddSocketSite); ok {
		r0 = returnFunc(ctx, addSocketSiteInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.SiteAddSocketSite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.AddSocketSiteInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, addSocketSiteInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SocketSiteClient_SiteAddSocketSite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SiteAddSocketSite'
type SocketSiteClient_SiteAddSocketSite_Call struct {
	*mock.Call
}

// SiteAddSocketSite is a helper method to define mock.On call
//   - ctx context.Context
//   - addSocketSiteInput cato_models.AddSocketSiteInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *SocketSiteClient_Expecter) SiteAddSocketSite(ctx interface{}, addSocketSiteInput interface{}, accountID interface{}, interceptors ...interface{}) *SocketSiteClient_SiteAddSocketSite_Call {
	return &SocketSiteClient_SiteAddSocketSite_Call{Call: _e.mock.On("SiteAddSocketSite",
		append([]interface{}{ctx, addSocketSiteInput, accountID}, interceptors...)...)}
}

func (_c *SocketSiteClient_SiteAddSocketSite_Call) Run(run func(ctx context.Context, addSocketSiteInput cato_models.AddSocketSiteInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *SocketSiteClient_SiteAddSocketSite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.AddSocketSiteInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.AddSocketSiteInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *SocketSiteClient_SiteAddSocketSite_Call) Return(siteAddSocketSite *cato_go_sdk.SiteAddSocketSite, err error) *SocketSiteClient_SiteAddSocketSite_Call {
	_c.Call.Return(siteAddSocketSite, err)
	return _c
}

func (_c *SocketSiteClient_SiteAddSocketSite_Call) RunAndReturn(run func(ctx context.Context, addSocketSiteInput cato_models.AddSocketSiteInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteAddSocketSite, error)) *SocketSiteClient_SiteAddSocketSite_Call {
	_c.Call.Return(run)
	return _c
}
