// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Yamashou/gqlgenc/clientv2"
	cato_go_sdk "github.com/catonetworks/cato-go-sdk"
	cato_models "github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewStaticHostClient creates a new instance of StaticHostClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStaticHostClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *StaticHostClient {
	mock := &StaticHostClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StaticHostClient is an autogenerated mock type for the StaticHostClient type
type StaticHostClient struct {
	mock.Mock
}

type StaticHostClient_Expecter struct {
	mock *mock.Mock
}

func (_m *StaticHostClient) EXPECT() *StaticHostClient_Expecter {
	return &StaticHostClient_Expecter{mock: &_m.Mock}
}

// SiteStaticHost provides a mock function for the type StaticHostClient
func (_mock *StaticHostClient) SiteStaticHost(ctx context.Context, accountID string, siteRefInput cato_models.SiteRefInput, hostID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteStaticHost, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, accountID, siteRefInput, hostID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, accountID, siteRefInput, hostID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SiteStaticHost")
	}

	var r0 *cato_go_sdk.SiteStaticHost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.SiteRefInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteStaticHost, error)); ok {
		return returnFunc(ctx, accountID, siteRefInput, hostID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cato_models.SiteRefInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.SiteStaticHost); ok {
		r0 = returnFunc(ctx, accountID, siteRefInput, hostID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.SiteStaticHost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cato_models.SiteRefInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, accountID, siteRefInput, hostID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StaticHostClient_SiteStaticHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SiteStaticHost'
type StaticHostClient_SiteStaticHost_Call struct {
	*mock.Call
}

// SiteStaticHost is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - siteRefInput cato_models.SiteRefInput
//   - hostID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *StaticHostClient_Expecter) SiteStaticHost(ctx interface{}, accountID interface{}, siteRefInput interface{}, hostID interface{}, interceptors ...interface{}) *StaticHostClient_SiteStaticHost_Call {
	return &StaticHostClient_SiteStaticHost_Call{Call: _e.mock.On("SiteStaticHost",
		append([]interface{}{ctx, accountID, siteRefInput, hostID}, interceptors...)...)}
}

func (_c *StaticHostClient_SiteStaticHost_Call) Run(run func(ctx context.Context, accountID string, siteRefInput cato_models.SiteRefInput, hostID string, interceptors ...clientv2.RequestInterceptor)) *StaticHostClient_SiteStaticHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cato_models.SiteRefInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.SiteRefInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *StaticHostClient_SiteStaticHost_Call) Return(siteStaticHost *cato_go_sdk.SiteStaticHost, err error) *StaticHostClient_SiteStaticHost_Call {
	_c.Call.Return(siteStaticHost, err)
	return _c
}

func (_c *StaticHostClient_SiteStaticHost_Call) RunAndReturn(run func(ctx context.Context, accountID string, siteRefInput cato_models.SiteRefInput, hostID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.SiteStaticHost, error)) *StaticHostClient_SiteStaticHost_Call {
	_c.Call.Return(run)
	return _c
}
