// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Yamashou/gqlgenc/clientv2"
	cato_go_sdk "github.com/catonetworks/cato-go-sdk"
	cato_models "github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewWanFirewallSubPolicyClient creates a new instance of WanFirewallSubPolicyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWanFirewallSubPolicyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WanFirewallSubPolicyClient {
	mock := &WanFirewallSubPolicyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WanFirewallSubPolicyClient is an autogenerated mock type for the WanFirewallSubPolicyClient type
type WanFirewallSubPolicyClient struct {
	mock.Mock
}

type WanFirewallSubPolicyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *WanFirewallSubPolicyClient) EXPECT() *WanFirewallSubPolicyClient_Expecter {
	return &WanFirewallSubPolicyClient_Expecter{mock: &_m.Mock}
}

// PolicyWanFirewall provides a mock function for the type WanFirewallSubPolicyClient
func (_mock *WanFirewallSubPolicyClient) PolicyWanFirewall(ctx context.Context, wanFirewallPolicyInput *cato_models.WanFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, wanFirewallPolicyInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, wanFirewallPolicyInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewall")
	}

	var r0 *cato_go_sdk.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.WanFirewallPolicyInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)); ok {
		return returnFunc(ctx, wanFirewallPolicyInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.WanFirewallPolicyInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.Policy); ok {
		r0 = returnFunc(ctx, wanFirewallPolicyInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.WanFirewallPolicyInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, wanFirewallPolicyInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanFirewallSubPolicyClient_PolicyWanFirewall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewall'
type WanFirewallSubPolicyClient_PolicyWanFirewall_Call struct {
	*mock.Call
}

// PolicyWanFirewall is a helper method to define mock.On call
//   - ctx context.Context
//   - wanFirewallPolicyInput *cato_models.WanFirewallPolicyInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanFirewallSubPolicyClient_Expecter) PolicyWanFirewall(ctx interface{}, wanFirewallPolicyInput interface{}, accountID interface{}, interceptors ...interface{}) *WanFirewallSubPolicyClient_PolicyWanFirewall_Call {
	return &WanFirewallSubPolicyClient_PolicyWanFirewall_Call{Call: _e.mock.On("PolicyWanFirewall",
		append([]interface{}{ctx, wanFirewallPolicyInput, accountID}, interceptors...)...)}
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewall_Call) Run(run func(ctx context.Context, wanFirewallPolicyInput *cato_models.WanFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanFirewallSubPolicyClient_PolicyWanFirewall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.WanFirewallPolicyInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.WanFirewallPolicyInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewall_Call) Return(policy *cato_go_sdk.Policy, err error) *WanFirewallSubPolicyClient_PolicyWanFirewall_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewall_Call) RunAndReturn(run func(ctx context.Context, wanFirewallPolicyInput *cato_models.WanFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)) *WanFirewallSubPolicyClient_PolicyWanFirewall_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallAddSubPolicy provides a mock function for the type WanFirewallSubPolicyClient
func (_mock *WanFirewallSubPolicyClient) PolicyWanFirewallAddSubPolicy(ctx context.Context, wanFirewallAddSubPolicyInput cato_models.WanFirewallAddSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallAddSubPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, wanFirewallAddSubPolicyInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, wanFirewallAddSubPolicyInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallAddSubPolicy")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallAddSubPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.WanFirewallAddSubPolicyInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallAddSubPolicy, error)); ok {
		return returnFunc(ctx, wanFirewallAddSubPolicyInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.WanFirewallAddSubPolicyInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallAddSubPolicy); ok {
		r0 = returnFunc(ctx, wanFirewallAddSubPolicyInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallAddSubPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.WanFirewallAddSubPolicyInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, wanFirewallAddSubPolicyInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallAddSubPolicy'
type WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call struct {
	*mock.Call
}

// PolicyWanFirewallAddSubPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - wanFirewallAddSubPolicyInput cato_models.WanFirewallAddSubPolicyInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanFirewallSubPolicyClient_Expecter) PolicyWanFirewallAddSubPolicy(ctx interface{}, wanFirewallAddSubPolicyInput interface{}, accountID interface{}, interceptors ...interface{}) *WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call {
	return &WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call{Call: _e.mock.On("PolicyWanFirewallAddSubPolicy",
		append([]interface{}{ctx, wanFirewallAddSubPolicyInput, accountID}, interceptors...)...)}
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call) Run(run func(ctx context.Context, wanFirewallAddSubPolicyInput cato_models.WanFirewallAddSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.WanFirewallAddSubPolicyInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.WanFirewallAddSubPolicyInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call) Return(policyWanFirewallAddSubPolicy *cato_go_sdk.PolicyWanFirewallAddSubPolicy, err error) *WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call {
	_c.Call.Return(policyWanFirewallAddSubPolicy, err)
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call) RunAndReturn(run func(ctx context.Context, wanFirewallAddSubPolicyInput cato_models.WanFirewallAddSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallAddSubPolicy, error)) *WanFirewallSubPolicyClient_PolicyWanFirewallAddSubPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallPublishPolicyRevision provides a mock function for the type WanFirewallSubPolicyClient
func (_mock *WanFirewallSubPolicyClient) PolicyWanFirewallPublishPolicyRevision(ctx context.Context, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, policyPublishRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, policyPublishRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallPublishPolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallPublishPolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, error)); ok {
		return returnFunc(ctx, policyPublishRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallPublishPolicyRevision); ok {
		r0 = returnFunc(ctx, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallPublishPolicyRevision'
type WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call struct {
	*mock.Call
}

// PolicyWanFirewallPublishPolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanFirewallSubPolicyClient_Expecter) PolicyWanFirewallPublishPolicyRevision(ctx interface{}, policyPublishRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call {
	return &WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call{Call: _e.mock.On("PolicyWanFirewallPublishPolicyRevision",
		append([]interface{}{ctx, policyPublishRevisionInput, accountID}, interceptors...)...)}
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call) Run(run func(ctx context.Context, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.PolicyPublishRevisionInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.PolicyPublishRevisionInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call) Return(policyWanFirewallPublishPolicyRevision *cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, err error) *WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call {
	_c.Call.Return(policyWanFirewallPublishPolicyRevision, err)
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call) RunAndReturn(run func(ctx context.Context, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, error)) *WanFirewallSubPolicyClient_PolicyWanFirewallPublishPolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallRemoveSubPolicy provides a mock function for the type WanFirewallSubPolicyClient
func (_mock *WanFirewallSubPolicyClient) PolicyWanFirewallRemoveSubPolicy(ctx context.Context, wanFirewallRemoveSubPolicyInput cato_models.WanFirewallRemoveSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallRemoveSubPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, wanFirewallRemoveSubPolicyInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, wanFirewallRemoveSubPolicyInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallRemoveSubPolicy")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallRemoveSubPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.WanFirewallRemoveSubPolicyInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallRemoveSubPolicy, error)); ok {
		return returnFunc(ctx, wanFirewallRemoveSubPolicyInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.WanFirewallRemoveSubPolicyInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallRemoveSubPolicy); ok {
		r0 = returnFunc(ctx, wanFirewallRemoveSubPolicyInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallRemoveSubPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.WanFirewallRemoveSubPolicyInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, wanFirewallRemoveSubPolicyInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallRemoveSubPolicy'
type WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call struct {
	*mock.Call
}

// PolicyWanFirewallRemoveSubPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - wanFirewallRemoveSubPolicyInput cato_models.WanFirewallRemoveSubPolicyInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanFirewallSubPolicyClient_Expecter) PolicyWanFirewallRemoveSubPolicy(ctx interface{}, wanFirewallRemoveSubPolicyInput interface{}, accountID interface{}, interceptors ...interface{}) *WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call {
	return &WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call{Call: _e.mock.On("PolicyWanFirewallRemoveSubPolicy",
		append([]interface{}{ctx, wanFirewallRemoveSubPolicyInput, accountID}, interceptors...)...)}
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call) Run(run func(ctx context.Context, wanFirewallRemoveSubPolicyInput cato_models.WanFirewallRemoveSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.WanFirewallRemoveSubPolicyInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.WanFirewallRemoveSubPolicyInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call) Return(policyWanFirewallRemoveSubPolicy *cato_go_sdk.PolicyWanFirewallRemoveSubPolicy, err error) *WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call {
	_c.Call.Return(policyWanFirewallRemoveSubPolicy, err)
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call) RunAndReturn(run func(ctx context.Context, wanFirewallRemoveSubPolicyInput cato_models.WanFirewallRemoveSubPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallRemoveSubPolicy, error)) *WanFirewallSubPolicyClient_PolicyWanFirewallRemoveSubPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallUpdateRule provides a mock function for the type WanFirewallSubPolicyClient
func (_mock *WanFirewallSubPolicyClient) PolicyWanFirewallUpdateRule(ctx context.Context, wanFirewallUpdateRuleInput cato_models.WanFirewallUpdateRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallUpdateRule, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, wanFirewallUpdateRuleInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, wanFirewallUpdateRuleInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallUpdateRule")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallUpdateRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.WanFirewallUpdateRuleInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallUpdateRule, error)); ok {
		return returnFunc(ctx, wanFirewallUpdateRuleInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.WanFirewallUpdateRuleInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallUpdateRule); ok {
		r0 = returnFunc(ctx, wanFirewallUpdateRuleInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallUpdateRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.WanFirewallUpdateRuleInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, wanFirewallUpdateRuleInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallUpdateRule'
type WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call struct {
	*mock.Call
}

// PolicyWanFirewallUpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - wanFirewallUpdateRuleInput cato_models.WanFirewallUpdateRuleInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanFirewallSubPolicyClient_Expecter) PolicyWanFirewallUpdateRule(ctx interface{}, wanFirewallUpdateRuleInput interface{}, accountID interface{}, interceptors ...interface{}) *WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call {
	return &WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call{Call: _e.mock.On("PolicyWanFirewallUpdateRule",
		append([]interface{}{ctx, wanFirewallUpdateRuleInput, accountID}, interceptors...)...)}
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call) Run(run func(ctx context.Context, wanFirewallUpdateRuleInput cato_models.WanFirewallUpdateRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.WanFirewallUpdateRuleInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.WanFirewallUpdateRuleInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call) Return(policyWanFirewallUpdateRule *cato_go_sdk.PolicyWanFirewallUpdateRule, err error) *WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call {
	_c.Call.Return(policyWanFirewallUpdateRule, err)
	return _c
}

func (_c *WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call) RunAndReturn(run func(ctx context.Context, wanFirewallUpdateRuleInput cato_models.WanFirewallUpdateRuleInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallUpdateRule, error)) *WanFirewallSubPolicyClient_PolicyWanFirewallUpdateRule_Call {
	_c.Call.Return(run)
	return _c
}
