// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/Yamashou/gqlgenc/clientv2"
	"github.com/catonetworks/cato-go-sdk"
	"github.com/catonetworks/cato-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewWanRulesIndexClient creates a new instance of WanRulesIndexClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWanRulesIndexClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WanRulesIndexClient {
	mock := &WanRulesIndexClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WanRulesIndexClient is an autogenerated mock type for the WanRulesIndexClient type
type WanRulesIndexClient struct {
	mock.Mock
}

type WanRulesIndexClient_Expecter struct {
	mock *mock.Mock
}

func (_m *WanRulesIndexClient) EXPECT() *WanRulesIndexClient_Expecter {
	return &WanRulesIndexClient_Expecter{mock: &_m.Mock}
}

// PolicyWanFirewall provides a mock function for the type WanRulesIndexClient
func (_mock *WanRulesIndexClient) PolicyWanFirewall(ctx context.Context, wanFirewallPolicyInput *cato_models.WanFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, wanFirewallPolicyInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, wanFirewallPolicyInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewall")
	}

	var r0 *cato_go_sdk.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.WanFirewallPolicyInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)); ok {
		return returnFunc(ctx, wanFirewallPolicyInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.WanFirewallPolicyInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.Policy); ok {
		r0 = returnFunc(ctx, wanFirewallPolicyInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.WanFirewallPolicyInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, wanFirewallPolicyInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanRulesIndexClient_PolicyWanFirewall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewall'
type WanRulesIndexClient_PolicyWanFirewall_Call struct {
	*mock.Call
}

// PolicyWanFirewall is a helper method to define mock.On call
//   - ctx context.Context
//   - wanFirewallPolicyInput *cato_models.WanFirewallPolicyInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanRulesIndexClient_Expecter) PolicyWanFirewall(ctx interface{}, wanFirewallPolicyInput interface{}, accountID interface{}, interceptors ...interface{}) *WanRulesIndexClient_PolicyWanFirewall_Call {
	return &WanRulesIndexClient_PolicyWanFirewall_Call{Call: _e.mock.On("PolicyWanFirewall",
		append([]interface{}{ctx, wanFirewallPolicyInput, accountID}, interceptors...)...)}
}

func (_c *WanRulesIndexClient_PolicyWanFirewall_Call) Run(run func(ctx context.Context, wanFirewallPolicyInput *cato_models.WanFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanRulesIndexClient_PolicyWanFirewall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.WanFirewallPolicyInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.WanFirewallPolicyInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewall_Call) Return(policy *cato_go_sdk.Policy, err error) *WanRulesIndexClient_PolicyWanFirewall_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewall_Call) RunAndReturn(run func(ctx context.Context, wanFirewallPolicyInput *cato_models.WanFirewallPolicyInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.Policy, error)) *WanRulesIndexClient_PolicyWanFirewall_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallCreatePolicyRevision provides a mock function for the type WanRulesIndexClient
func (_mock *WanRulesIndexClient) PolicyWanFirewallCreatePolicyRevision(ctx context.Context, policyCreateRevisionInput cato_models.PolicyCreateRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallCreatePolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, policyCreateRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, policyCreateRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallCreatePolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallCreatePolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.PolicyCreateRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallCreatePolicyRevision, error)); ok {
		return returnFunc(ctx, policyCreateRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.PolicyCreateRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallCreatePolicyRevision); ok {
		r0 = returnFunc(ctx, policyCreateRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallCreatePolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.PolicyCreateRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, policyCreateRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallCreatePolicyRevision'
type WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call struct {
	*mock.Call
}

// PolicyWanFirewallCreatePolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - policyCreateRevisionInput cato_models.PolicyCreateRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanRulesIndexClient_Expecter) PolicyWanFirewallCreatePolicyRevision(ctx interface{}, policyCreateRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call {
	return &WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call{Call: _e.mock.On("PolicyWanFirewallCreatePolicyRevision",
		append([]interface{}{ctx, policyCreateRevisionInput, accountID}, interceptors...)...)}
}

func (_c *WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call) Run(run func(ctx context.Context, policyCreateRevisionInput cato_models.PolicyCreateRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.PolicyCreateRevisionInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.PolicyCreateRevisionInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call) Return(policyWanFirewallCreatePolicyRevision *cato_go_sdk.PolicyWanFirewallCreatePolicyRevision, err error) *WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call {
	_c.Call.Return(policyWanFirewallCreatePolicyRevision, err)
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call) RunAndReturn(run func(ctx context.Context, policyCreateRevisionInput cato_models.PolicyCreateRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallCreatePolicyRevision, error)) *WanRulesIndexClient_PolicyWanFirewallCreatePolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallDiscardPolicyRevision provides a mock function for the type WanRulesIndexClient
func (_mock *WanRulesIndexClient) PolicyWanFirewallDiscardPolicyRevision(ctx context.Context, policyDiscardRevisionInput *cato_models.PolicyDiscardRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallDiscardPolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, policyDiscardRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, policyDiscardRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallDiscardPolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallDiscardPolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.PolicyDiscardRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallDiscardPolicyRevision, error)); ok {
		return returnFunc(ctx, policyDiscardRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.PolicyDiscardRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallDiscardPolicyRevision); ok {
		r0 = returnFunc(ctx, policyDiscardRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallDiscardPolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.PolicyDiscardRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, policyDiscardRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallDiscardPolicyRevision'
type WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call struct {
	*mock.Call
}

// PolicyWanFirewallDiscardPolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - policyDiscardRevisionInput *cato_models.PolicyDiscardRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanRulesIndexClient_Expecter) PolicyWanFirewallDiscardPolicyRevision(ctx interface{}, policyDiscardRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call {
	return &WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call{Call: _e.mock.On("PolicyWanFirewallDiscardPolicyRevision",
		append([]interface{}{ctx, policyDiscardRevisionInput, accountID}, interceptors...)...)}
}

func (_c *WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call) Run(run func(ctx context.Context, policyDiscardRevisionInput *cato_models.PolicyDiscardRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.PolicyDiscardRevisionInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.PolicyDiscardRevisionInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call) Return(policyWanFirewallDiscardPolicyRevision *cato_go_sdk.PolicyWanFirewallDiscardPolicyRevision, err error) *WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call {
	_c.Call.Return(policyWanFirewallDiscardPolicyRevision, err)
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call) RunAndReturn(run func(ctx context.Context, policyDiscardRevisionInput *cato_models.PolicyDiscardRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallDiscardPolicyRevision, error)) *WanRulesIndexClient_PolicyWanFirewallDiscardPolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallMoveSection provides a mock function for the type WanRulesIndexClient
func (_mock *WanRulesIndexClient) PolicyWanFirewallMoveSection(ctx context.Context, policyMoveSectionInput cato_models.PolicyMoveSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallMoveSection, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, policyMoveSectionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, policyMoveSectionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallMoveSection")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallMoveSection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.PolicyMoveSectionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallMoveSection, error)); ok {
		return returnFunc(ctx, policyMoveSectionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cato_models.PolicyMoveSectionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallMoveSection); ok {
		r0 = returnFunc(ctx, policyMoveSectionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallMoveSection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cato_models.PolicyMoveSectionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, policyMoveSectionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanRulesIndexClient_PolicyWanFirewallMoveSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallMoveSection'
type WanRulesIndexClient_PolicyWanFirewallMoveSection_Call struct {
	*mock.Call
}

// PolicyWanFirewallMoveSection is a helper method to define mock.On call
//   - ctx context.Context
//   - policyMoveSectionInput cato_models.PolicyMoveSectionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanRulesIndexClient_Expecter) PolicyWanFirewallMoveSection(ctx interface{}, policyMoveSectionInput interface{}, accountID interface{}, interceptors ...interface{}) *WanRulesIndexClient_PolicyWanFirewallMoveSection_Call {
	return &WanRulesIndexClient_PolicyWanFirewallMoveSection_Call{Call: _e.mock.On("PolicyWanFirewallMoveSection",
		append([]interface{}{ctx, policyMoveSectionInput, accountID}, interceptors...)...)}
}

func (_c *WanRulesIndexClient_PolicyWanFirewallMoveSection_Call) Run(run func(ctx context.Context, policyMoveSectionInput cato_models.PolicyMoveSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanRulesIndexClient_PolicyWanFirewallMoveSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cato_models.PolicyMoveSectionInput
		if args[1] != nil {
			arg1 = args[1].(cato_models.PolicyMoveSectionInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallMoveSection_Call) Return(policyWanFirewallMoveSection *cato_go_sdk.PolicyWanFirewallMoveSection, err error) *WanRulesIndexClient_PolicyWanFirewallMoveSection_Call {
	_c.Call.Return(policyWanFirewallMoveSection, err)
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallMoveSection_Call) RunAndReturn(run func(ctx context.Context, policyMoveSectionInput cato_models.PolicyMoveSectionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallMoveSection, error)) *WanRulesIndexClient_PolicyWanFirewallMoveSection_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallPublishPolicyRevision provides a mock function for the type WanRulesIndexClient
func (_mock *WanRulesIndexClient) PolicyWanFirewallPublishPolicyRevision(ctx context.Context, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, policyPublishRevisionInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, policyPublishRevisionInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallPublishPolicyRevision")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallPublishPolicyRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, error)); ok {
		return returnFunc(ctx, policyPublishRevisionInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallPublishPolicyRevision); ok {
		r0 = returnFunc(ctx, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.PolicyPublishRevisionInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, policyPublishRevisionInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallPublishPolicyRevision'
type WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call struct {
	*mock.Call
}

// PolicyWanFirewallPublishPolicyRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanRulesIndexClient_Expecter) PolicyWanFirewallPublishPolicyRevision(ctx interface{}, policyPublishRevisionInput interface{}, accountID interface{}, interceptors ...interface{}) *WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call {
	return &WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call{Call: _e.mock.On("PolicyWanFirewallPublishPolicyRevision",
		append([]interface{}{ctx, policyPublishRevisionInput, accountID}, interceptors...)...)}
}

func (_c *WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call) Run(run func(ctx context.Context, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.PolicyPublishRevisionInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.PolicyPublishRevisionInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv2.RequestInterceptor)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call) Return(policyWanFirewallPublishPolicyRevision *cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, err error) *WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call {
	_c.Call.Return(policyWanFirewallPublishPolicyRevision, err)
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call) RunAndReturn(run func(ctx context.Context, policyPublishRevisionInput *cato_models.PolicyPublishRevisionInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallPublishPolicyRevision, error)) *WanRulesIndexClient_PolicyWanFirewallPublishPolicyRevision_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallReorderPolicy provides a mock function for the type WanRulesIndexClient
func (_mock *WanRulesIndexClient) PolicyWanFirewallReorderPolicy(ctx context.Context, wanFirewallPolicyMutationInput *cato_models.WanFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallReorderPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallReorderPolicy")
	}

	var r0 *cato_go_sdk.PolicyWanFirewallReorderPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.WanFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallReorderPolicy, error)); ok {
		return returnFunc(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cato_models.WanFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) *cato_go_sdk.PolicyWanFirewallReorderPolicy); ok {
		r0 = returnFunc(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.PolicyWanFirewallReorderPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cato_models.WanFirewallPolicyMutationInput, cato_models.PolicyReorderInput, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallReorderPolicy'
type WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call struct {
	*mock.Call
}

// PolicyWanFirewallReorderPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - wanFirewallPolicyMutationInput *cato_models.WanFirewallPolicyMutationInput
//   - policyReorderInput cato_models.PolicyReorderInput
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanRulesIndexClient_Expecter) PolicyWanFirewallReorderPolicy(ctx interface{}, wanFirewallPolicyMutationInput interface{}, policyReorderInput interface{}, accountID interface{}, interceptors ...interface{}) *WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call {
	return &WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call{Call: _e.mock.On("PolicyWanFirewallReorderPolicy",
		append([]interface{}{ctx, wanFirewallPolicyMutationInput, policyReorderInput, accountID}, interceptors...)...)}
}

func (_c *WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call) Run(run func(ctx context.Context, wanFirewallPolicyMutationInput *cato_models.WanFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cato_models.WanFirewallPolicyMutationInput
		if args[1] != nil {
			arg1 = args[1].(*cato_models.WanFirewallPolicyMutationInput)
		}
		var arg2 cato_models.PolicyReorderInput
		if args[2] != nil {
			arg2 = args[2].(cato_models.PolicyReorderInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 4 {
			variadicArgs = args[4].([]clientv2.RequestInterceptor)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call) Return(policyWanFirewallReorderPolicy *cato_go_sdk.PolicyWanFirewallReorderPolicy, err error) *WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call {
	_c.Call.Return(policyWanFirewallReorderPolicy, err)
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call) RunAndReturn(run func(ctx context.Context, wanFirewallPolicyMutationInput *cato_models.WanFirewallPolicyMutationInput, policyReorderInput cato_models.PolicyReorderInput, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.PolicyWanFirewallReorderPolicy, error)) *WanRulesIndexClient_PolicyWanFirewallReorderPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallRulesIndex provides a mock function for the type WanRulesIndexClient
func (_mock *WanRulesIndexClient) PolicyWanFirewallRulesIndex(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.WanRulesIndexPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallRulesIndex")
	}

	var r0 *cato_go_sdk.WanRulesIndexPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.WanRulesIndexPolicy, error)); ok {
		return returnFunc(ctx, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) *cato_go_sdk.WanRulesIndexPolicy); ok {
		r0 = returnFunc(ctx, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.WanRulesIndexPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallRulesIndex'
type WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call struct {
	*mock.Call
}

// PolicyWanFirewallRulesIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanRulesIndexClient_Expecter) PolicyWanFirewallRulesIndex(ctx interface{}, accountID interface{}, interceptors ...interface{}) *WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call {
	return &WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call{Call: _e.mock.On("PolicyWanFirewallRulesIndex",
		append([]interface{}{ctx, accountID}, interceptors...)...)}
}

func (_c *WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call) Run(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv2.RequestInterceptor)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call) Return(wanRulesIndexPolicy *cato_go_sdk.WanRulesIndexPolicy, err error) *WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call {
	_c.Call.Return(wanRulesIndexPolicy, err)
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call) RunAndReturn(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.WanRulesIndexPolicy, error)) *WanRulesIndexClient_PolicyWanFirewallRulesIndex_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyWanFirewallSectionsIndex provides a mock function for the type WanRulesIndexClient
func (_mock *WanRulesIndexClient) PolicyWanFirewallSectionsIndex(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.WanSectionsIndexPolicy, error) {
	var tmpRet mock.Arguments
	if len(interceptors) > 0 {
		tmpRet = _mock.Called(ctx, accountID, interceptors)
	} else {
		tmpRet = _mock.Called(ctx, accountID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PolicyWanFirewallSectionsIndex")
	}

	var r0 *cato_go_sdk.WanSectionsIndexPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) (*cato_go_sdk.WanSectionsIndexPolicy, error)); ok {
		return returnFunc(ctx, accountID, interceptors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv2.RequestInterceptor) *cato_go_sdk.WanSectionsIndexPolicy); ok {
		r0 = returnFunc(ctx, accountID, interceptors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cato_go_sdk.WanSectionsIndexPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv2.RequestInterceptor) error); ok {
		r1 = returnFunc(ctx, accountID, interceptors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyWanFirewallSectionsIndex'
type WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call struct {
	*mock.Call
}

// PolicyWanFirewallSectionsIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - interceptors ...clientv2.RequestInterceptor
func (_e *WanRulesIndexClient_Expecter) PolicyWanFirewallSectionsIndex(ctx interface{}, accountID interface{}, interceptors ...interface{}) *WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call {
	return &WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call{Call: _e.mock.On("PolicyWanFirewallSectionsIndex",
		append([]interface{}{ctx, accountID}, interceptors...)...)}
}

func (_c *WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call) Run(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor)) *WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv2.RequestInterceptor
		var variadicArgs []clientv2.RequestInterceptor
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv2.RequestInterceptor)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call) Return(wanSectionsIndexPolicy *cato_go_sdk.WanSectionsIndexPolicy, err error) *WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call {
	_c.Call.Return(wanSectionsIndexPolicy, err)
	return _c
}

func (_c *WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call) RunAndReturn(run func(ctx context.Context, accountID string, interceptors ...clientv2.RequestInterceptor) (*cato_go_sdk.WanSectionsIndexPolicy, error)) *WanRulesIndexClient_PolicyWanFirewallSectionsIndex_Call {
	_c.Call.Return(run)
	return _c
}
